<a href="https://colab.research.google.com/github/sheninyee/sdis-solvathon-2026-team-theSouperSolvers/blob/main/solveathon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [190]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [191]:
data_path = '/content/drive/My Drive/grants-search-202608182008.csv'
df = pd.read_csv(data_path)

df.info()
df.head(60)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1662 entries, 0 to 1661
Data columns (total 40 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   opportunity_id                     1662 non-null   object
 1   opportunity_number                 1662 non-null   object
 2   opportunity_title                  1662 non-null   object
 3   opportunity_status                 1662 non-null   object
 4   agency_code                        1662 non-null   object
 5   category                           1662 non-null   object
 6   category_explanation               29 non-null     object
 7   post_date                          1662 non-null   object
 8   close_date                         1005 non-null   object
 9   close_date_description             291 non-null    object
 10  archive_date                       954 non-null    object
 11  is_cost_sharing                    1662 non-null   bool
 12  expected_number_of_awards          940 non-null    float64
 13  estimated_total_program_funding    914 non-null    float64
 14  award_floor                        664 non-null    float64
 15  award_ceiling                      798 non-null    float64
 16  additional_info_url                757 non-null    object
 17  additional_info_url_description    741 non-null    object
 18  opportunity_assistance_listings    1661 non-null   object
 19  funding_instruments                1662 non-null   object
 20  funding_categories                 1662 non-null   object
 21  funding_category_description       143 non-null    object
 22  applicant_types                    1662 non-null   object
 23  applicant_eligibility_description  1285 non-null   object
 24  agency_name                        1662 non-null   object
 25  top_level_agency_name              1662 non-null   object
 26  agency_contact_description         1662 non-null   object
 27  agency_email_address               1613 non-null   object
 28  agency_email_address_description   1608 non-null   object
 29  is_forecast                        1662 non-null   bool
 30  forecasted_post_date               473 non-null    object
 31  forecasted_close_date              499 non-null    object
 32  forecasted_close_date_description  151 non-null    object
 33  forecasted_award_date              453 non-null    object
 34  forecasted_project_start_date      459 non-null    object
 35  fiscal_year                        559 non-null    float64
 36  created_at                         0 non-null      float64
 37  updated_at                         0 non-null      float64
 38  url                                1662 non-null   object
 39  summary_description                1662 non-null   object
dtypes: bool(2), float64(7), object(31)
memory usage: 496.8+ KB

,opportunity_id,opportunity_number,opportunity_title,opportunity_status,agency_code,category,category_explanation,post_date,close_date,close_date_description,...,forecasted_post_date,forecasted_close_date,forecasted_close_date_description,forecasted_award_date,forecasted_project_start_date,fiscal_year,created_at,updated_at,url,summary_description
0,3f8c97e2-901a-44c4-b9ac-b6b941c29d42,O-OVW-2026-172633,OVW Fiscal Year 2026 Grants to Improve the Cri...,posted,USDOJ-OJP-OVW,discretionary,NaN,2026-06-04,2026-08-18,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/3f8c97e...,"The ICJR Program assists Tribal, state, and lo..."
1,07f98e93-9564-44cf-ab5c-69ca0cfa218f,PAR-25-051,Blueprint Neurotherapeutics Network (BPN): Sma...,posted,HHS-NIH11,discretionary,NaN,2024-09-25,2026-08-18,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/07f98e9...,The Blueprint Neurotherapeutics Network (BPN) ...
2,0f7454eb-e5b6-458a-86eb-4d874a9f9d8f,HHS-2026-ACF-ACYF-AP-0003,Personal Responsibility Education Innovative S...,posted,HHS-ACF-FYSB,discretionary,NaN,2026-07-17,2026-08-18,Electronically submitted applications must be ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/0f7454e...,The Personal Responsibility Education Program-...
3,a9a78fab-33d8-4a34-a2de-c7571df8b19b,23-618,"Decision, Risk and Management Sciences - Docto...",posted,NSF,discretionary,NaN,2023-08-25,2026-08-18,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/a9a78fa...,"The Decision, Risk and Management Sciences Pro..."
4,83f7a3f7-9a94-46dc-b9da-d8300efb69c1,SB-OIT-STEP-2026-01,State Trade Expansion Program 2026,posted,SBA,discretionary,NaN,2026-07-10,2026-08-18,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/83f7a3f...,<p>State Trade Expansion Program</p>
5,91d17473-9a2e-433b-8daa-a76f47721574,NNH25ZDA001N-RIA,ROSES25: F.17 Research Initiation Awards,posted,NASA-HQ,discretionary,NaN,2026-05-20,2026-08-18,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/91d1747...,"<p><strong>NOTICE: Amended May 20, 2026. This ..."
6,9c36e35a-beae-4bf4-9bb1-ef5927677555,FR-CCD-24-023,FY24 Little Rock Port Authority Transload Yard...,posted,DOT-FRA,discretionary,NaN,2026-08-12,2026-08-18,No Explanation,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/9c36e35...,Little Rock Port Authority Transload Yard
7,c2235197-1004-43b5-b0e4-ee599d64fd13,PD-23-1321,"Decision, Risk and Management Sciences",posted,NSF,discretionary,NaN,2023-05-11,2026-08-18,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/c223519...,"The Decision, Risk and Management Sciences Pro..."
8,145d1cb2-34a7-4f79-b927-341045f54938,USDA-FNA-SNAP-2026-EVS,FY 2026 SNAP Earnings Verification Support Grant,posted,USDA-FNS1,discretionary,NaN,2026-07-16,2026-08-19,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/145d1cb...,<p>The USDA’s Food and Nutrition Administratio...
9,2a188bdf-3d4a-4021-9f9d-dafce74537ba,HHS-2026-ACF-ACYF-CY-0160,National Communication System for Runaway and ...,posted,HHS-ACF-FYSB,discretionary,NaN,2026-07-21,2026-08-19,Electronically submitted applications must be ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/2a188bd...,​​The Division of Runaway and Homeless Youth w...
10,19553c47-f333-4b57-b6c3-74f38305903f,23-601,Research Experiences for Undergraduates,posted,NSF,discretionary,NaN,2023-06-29,2026-08-19,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/19553c4...,The Research Experiences for Undergraduates (R...
11,f58877bf-d0ad-43f7-8ae4-92382f4e0d0d,PA-FPT-26-001,National Training Center for Family Planning,posted,HHS-OPHS,discretionary,NaN,2026-07-02,2026-08-19,Applications must be submitted electronically ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/f58877b...,The purpose of this funding opportunity is to ...
12,758eb232-aa13-4c39-a651-e6429d961b03,RFA-FD-26-012,Use of Digital Health Technologies in Clinical...,posted,HHS-FDA,discretionary,NaN,2026-07-20,2026-08-20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/758eb23...,<p>The purpose of this Notice of Funding Oppor...
13,7dbda489-7738-473c-a407-2e15b7799566,O-BJA-2026-172654,BJA FY 2025/2026 Project Safe Neighborhoods Fo...,posted,USDOJ-OJP-BJA,other,Formula,2026-07-13,2026-08-20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/7dbda48...,This is a notice of funding opportunity (NOFO)...
14,b3fc2fad-6829-4466-a040-8e5d7df3b6fc,AMERICANSPACESSTARTUPLAB-2026,StartUP Lab: U.S.-Albania Economic Leadership...,posted,DOS-ALB,discretionary,NaN,2026-07-20,2026-08-20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/b3fc2fa...,<p>1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<stro...
15,cfd01f0a-d9c5-42c4-89e3-445d2b1bf16d,DFOP0019426,Leveraging Academic Institutions and Judicial ...,posted,DOS-DRL,discretionary,NaN,2026-07-21,2026-08-20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/cfd01f0...,"The U.S. Department of State, Bureau of Democr..."
16,b72b08c2-cfde-4c1c-9ba2-deb5e9aec8a5,PDS-APS-FY26-01,"U.S-Nigeria Creative, Digital, & Innovation Ec...",posted,DOS-NGA,discretionary,NaN,2026-07-22,2026-08-20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/b72b08c...,<p>The U.S. Department of State’s U.S. Consula...
17,dfd24081-d0e0-4630-8988-bbe1ee8f2689,RFA-FD-26-009,Education and Outreach to Tribal Producers thr...,posted,HHS-FDA,discretionary,NaN,2026-07-20,2026-08-20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/dfd2408...,<p>The primary purpose of this program is to d...
18,2f434e81-c476-49bb-a7e6-9a320c907cd9,DFOP0019193,Pax Silica Artificial Intelligence Assistance ...,posted,DOS-EB,discretionary,NaN,2026-08-14,2026-08-20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/2f434e8...,Leveraging foreign assistance from the Pax Fun...
19,9c2d325f-bb42-4d98-b60b-65422a5c38b8,AMERICANSPACESGAMEON-2026,GameON – U.S.-Albania E-Sports and Innovation,posted,DOS-ALB,discretionary,NaN,2026-07-20,2026-08-20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/9c2d325...,"<strong style=""color: windowtext;""><em>1.&nbsp..."
20,9f4e0eea-6330-4011-8742-617103f10bd8,PDS-BUE-2026-07,Subnational Industrial Innovation and Resilien...,posted,DOS-ARG,discretionary,NaN,2026-07-27,2026-08-20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/9f4e0ee...,<p>The U.S. Embassy Buenos Aires announces an ...
21,c9928432-25de-46e2-96b7-f4d3cb4ca7b0,AMERICANSPACESCYBERNEXT-2026,CyberNext: Advance Cybersecurity and AI Readiness,posted,DOS-ALB,discretionary,NaN,2026-07-20,2026-08-20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/c992843...,"<p><strong style=""color: black;""><em>Project B..."
22,c36eed46-2c0c-46e0-830a-c15274a1ee00,PDS-BUE-2026-06,U.S.-Argentina Alumni Summit,posted,DOS-ARG,discretionary,NaN,2026-07-27,2026-08-20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/c36eed4...,<p>The U.S. Embassy Buenos Aires announces an ...
23,cf7687ca-0614-44a6-8f46-08723d8df092,DHS-26-NPD-107-00-01,Fiscal Year 2026 National Incident Management ...,posted,DHS-DHS,mandatory,NaN,2026-07-17,2026-08-20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/cf7687c...,<p>The purpose of the Fiscal Year (FY) 2026 NI...
24,14e416ba-c983-42f9-be72-003e5f8b4a28,HHS-2026-ACF-ACYF-CO-0040,Technology Enhanced Adoptive Family Recruiting...,posted,HHS-ACF-CB,discretionary,NaN,2026-07-22,2026-08-21,Electronically submitted applications must be ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/14e416b...,This program will fund projects focused on tec...
25,64b21b29-7210-4d55-9630-29a9bbdf9dd8,RFA-FD-26-011,"Research, Education, and Outreach on Botanical...",posted,HHS-FDA,discretionary,NaN,2026-07-22,2026-08-21,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/64b21b2...,<p>The purpose of this funding opportunity is ...
26,da9ea956-a099-4ac0-ae24-3f9b001ee9a0,DOS-KAZ-ALM-PDS-26-001,Access Alumni Outreach and Engagement and Engl...,posted,DOS-KAZ,discretionary,NaN,2026-07-21,2026-08-21,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/da9ea95...,<p><strong>Funding Instrument Type:</strong> C...
27,f21ed65a-a584-4f18-b035-67652078ad06,DOS-LONDON-PD-2026-02,Liberty Under Law: The Shared Anglo-American T...,posted,DOS-GBR,discretionary,NaN,2026-07-20,2026-08-21,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/f21ed65...,"<p><span style=""color: black;"">The U.S. Depart..."
28,361be62f-48af-4751-b81e-5c829eecdafa,DFOP0019542,Promoting Civilizational Values,posted,DOS-DRL,discretionary,NaN,2026-08-07,2026-08-21,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/361be62...,DRL requests proposals to strengthen the abili...
29,1be83608-dcf2-4539-97fa-414d4c8ecaaa,2026-NIST-MEP-02,Manufacturing Extension Partnership Center Sta...,posted,DOC-NIST,discretionary,NaN,2026-07-22,2026-08-21,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/1be8360...,<p>The NIST Hollings Manufacturing Extension P...
30,92a87e8d-25fb-45d6-9b24-5143f0315a67,DFOP0018157,Data Analytics & AI to Counter Global Diversion,posted,DOS-ACN,discretionary,NaN,2026-07-16,2026-08-21,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/92a87e8...,This effort seeks to address multiple facets o...
31,d2e906e4-b4b0-40d3-b20c-12c22bbddfe0,RFA-FD-26-013,Cooperative Agreement to Support Shellfish Saf...,posted,HHS-FDA,discretionary,NaN,2026-07-22,2026-08-21,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/d2e906e...,<p>The purpose of this funding opportunity is ...
32,10c0d584-b356-49d0-8173-0e94a2eab1f5,RFA-FD-26-014,Federal and University Partnership to Improve ...,posted,HHS-FDA,discretionary,NaN,2026-07-23,2026-08-21,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/10c0d58...,<p>FDA is announcing the availability of funds...
33,9ea32117-e3af-440c-b8e3-00d3dd847463,FR-SEC-26-001,FY26 Transportation Emergency Response Training,posted,DOT-FRA,discretionary,NaN,2026-08-13,2026-08-21,No Explanation,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/9ea3211...,This grant will fund training for emergency re...
34,eb9d4f93-e7c5-4b6f-981e-b734308d39ea,O-OVC-2026-172691,OVC FY26 Invited to Apply Antiterrorism and Em...,posted,USDOJ-OJP-OVC,discretionary,NaN,2026-08-14,2026-08-21,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/eb9d4f9...,This is a notice of funding opportunity (NOFO)...
35,09b890ab-146f-4934-9309-ffe72fddd30f,USDA-NRCS-NHQ-RCPP-CLASSIC-26-NOFO000145,Regional Conservation Partnership Program (RCP...,posted,USDA-NRCS,discretionary,NaN,2026-06-23,2026-08-24,Applications must be received proposals by 4:5...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/09b890a...,<p><strong>Federal Awarding Agency Name: </str...
36,b8e41bf2-055d-4bde-bd67-144994abd33a,O-COPS-2026-172548,FY26 Collaborative Reform Initiative Program,posted,USDOJ-OJP-COPS,discretionary,NaN,2026-07-14,2026-08-24,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/b8e41bf...,The Office of Community Oriented Policing Serv...
37,7a05ac21-62c8-4c13-95de-2d5e8e80f851,FY26-PDS-USASEAN-02,2027 YSEALI ScamShield Regional Workshop,posted,DOS-ASEAN,discretionary,NaN,2026-07-22,2026-08-24,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/7a05ac2...,<p>The Public Diplomacy Sections (PDS) of the ...
38,239e6683-c301-4ee2-9794-cda512a24de5,HHS-2026-ACF-OCS-EAH-0027,Affordable Housing and Supportive Services Dem...,posted,HHS-ACF-OCS,discretionary,NaN,2026-07-24,2026-08-24,Electronically submitted applications must be ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/239e668...,The Office of Community Services (OCS) intends...
39,53569914-4323-4110-9680-2b264f0ae7d9,HHS-2026-ACF-OPRE-PV-0114,Reflective Supervision in Home Visiting Resear...,posted,HHS-ACF-OPRE,discretionary,NaN,2026-07-24,2026-08-24,Electronically submitted applications must be ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/5356991...,"The Office of Planning, Research and Evaluatio..."
40,09440b99-1e9a-4a02-b5cd-1549b83877b3,DFOP0018829,FY 2027 International Visitor Leadership Progr...,posted,DOS-ECA,discretionary,NaN,2026-06-24,2026-08-24,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/09440b9...,<p>The United States Department of State’s Bur...
41,86d33083-e00e-4d5b-b5e5-dac2693db06e,HHS-2026-ACF-OCS-ET-0029,Community Services Block Grant (CSBG) Communit...,posted,HHS-ACF-OCS,discretionary,NaN,2026-07-24,2026-08-24,Electronically submitted applications must be ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/86d3308...,This NOFO is modified. The email address and p...
42,e2d850ad-cd5d-4af4-82df-ba31865f7568,USDA-NRCS-NHQ-RCPP-AFA-26-NOFO0001451,Regional Conservation Partnership Program (RCP...,posted,USDA-NRCS,discretionary,NaN,2026-06-23,2026-08-24,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/e2d850a...,<p><br></p> \n<p><br></p> \n<p><strong>Federal...
43,6fda9fa9-8a53-48c8-b6a1-761fe0683635,HT942526LRPIPA,"DoW Lupus, Impact Award",posted,DOD-AMRAA,discretionary,NaN,2026-05-05,2026-08-24,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/6fda9fa...,<p>Summary: This funding mechanism supports hi...
44,795c0a29-510b-4b57-893a-d627b533ea6d,HT942526LRPIA,"DoW Lupus, Idea Award",posted,DOD-AMRAA,discretionary,NaN,2026-05-05,2026-08-24,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/795c0a2...,<p>Summary: This funding mechanism supports in...
45,5208056f-6e60-4509-8105-8bebd2ccab29,HT942526LRPTVDA,"DoW Lupus, Transformative Vision Development A...",posted,DOD-AMRAA,discretionary,NaN,2026-05-05,2026-08-24,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/5208056...,<p>Summary: This funding mechanism supports pl...
46,3ce9aff2-1ad9-4f82-abbf-3c44732640d8,HHS-2026-ACF-OCS-ET-0028,Community Services Block Grant (CSBG) Tribal C...,posted,HHS-ACF-OCS,discretionary,NaN,2026-07-24,2026-08-24,Electronically submitted applications must be ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/3ce9aff...,This NOFO is modified. The email address and p...
47,7f133801-c0e7-4967-826d-ed2419fa6206,SB-OEDNA-26-001,ONAA 7J-TCU Manufacturing NOFO FY2026,posted,SBA,discretionary,NaN,2026-07-24,2026-08-24,No Explanation,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/7f13380...,<p>The purpose of this Funding Opportunity Ann...
48,8fedc0bf-621a-4832-885c-8ae17b290747,O-COPS-2026-172561,FY26 Community Policing Development: Law Enfor...,posted,USDOJ-OJP-COPS,discretionary,NaN,2026-07-14,2026-08-24,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/8fedc0b...,The Office of Community Oriented Policing Serv...
49,a045e8e8-60f2-427a-b6d1-80f9d588dcbb,HHS-2026-ACF-OCS-ET-0030,Community Services Block Grant (CSBG) Essentia...,posted,HHS-ACF-OCS,discretionary,NaN,2026-07-24,2026-08-24,Electronically submitted applications must be ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/a045e8e...,This NOFO is modified. The email address and p...
50,e4d552b0-307d-4181-a6b9-92618d3963a3,HHS-2026-ACF-OCS-ET-0031,Community Services Block Grant (CSBG) Performa...,posted,HHS-ACF-OCS,discretionary,NaN,2026-07-24,2026-08-24,Electronically submitted applications must be ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/e4d552b...,This NOFO is modified. The email address and p...
51,e30a01a0-4ef9-466c-bed8-1bd2a9ef92b3,HT942526LRPTVA,"DoW Lupus, Transformative Vision Award",posted,DOD-AMRAA,discretionary,NaN,2026-05-05,2026-08-24,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/e30a01a...,<p>Summary: This funding mechanism supports in...
52,f867961f-f4de-47b1-8b18-51ddbe5531d6,O-COPS-2026-172560,FY26 Collaborative Reform Organizational Asses...,posted,USDOJ-OJP-COPS,discretionary,NaN,2026-07-14,2026-08-24,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/f867961...,The Office of Community Oriented Policing Serv...
53,56b71085-ed91-4468-b7eb-3a04bf840794,HR001126S0010,Decentralized Artificial Intelligence through ...,posted,DOD-DARPA-IPTO,discretionary,NaN,2026-06-10,2026-08-25,See Full Announcement for details.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/56b7108...,The DICE program seeks to develop the theory a...
54,c82c7aab-1dcf-4e82-8f18-86107c3bcf25,O-BJA-2026-172684,OJP FY 2026 Special Attorneys Program Round 7,posted,USDOJ-OJP-BJA,discretionary,NaN,2026-08-12,2026-08-25,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/c82c7aa...,This is a notice of funding opportunity (NOFO)...
55,b88775b5-9db4-4d78-861a-860df9449cd7,OFOP0003144,Enhancing Prison Population Management Through...,posted,DOS-INL,discretionary,NaN,2026-06-30,2026-08-25,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/b88775b...,"The project will divert low-risk, first-time o..."
56,ea961e6e-f500-482e-84e2-b7d9a7a6105b,23-586,Robert Noyce Teacher Scholarship Program,posted,NSF,discretionary,NaN,2023-05-09,2026-08-25,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/ea961e6...,The National Science FoundationRobert Noyce Te...
57,392cf284-d976-44c8-8515-265a3134e49a,FTA-2026-002-TPM-TRTR,FY 2026 Competitive Funding Opportunity: Publi...,posted,DOT-FTA,discretionary,NaN,2026-05-27,2026-08-25,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/392cf28...,<p>The Federal Transit Administration (FTA) an...
58,1115c1ae-29fe-4c8c-a8c0-b1541ee6d285,DFOP0019436,Legal Competency and Training Program in South...,posted,DOS-EAP,discretionary,NaN,2026-07-23,2026-08-25,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/1115c1a...,The overall goal of the project is to strength...
59,deb21960-8b7b-4507-84fd-3ad7a24fb22d,HHS-2026-ACL-AOA-LAEP-0055,Legal Assistance Enhancement Program Grants,posted,HHS-ACL,discretionary,NaN,2026-06-29,2026-08-25,Electronically submitted applications must be ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/deb2196...,To carry out Older Americans Act Section 307(a...

In [192]:
print(df.shape)

(1662, 40)

In [193]:
df[
    df["opportunity_number"]
    .fillna("")
    .str.split(";")
    .apply(lambda x: "DOT-HASS-FY26-DIIG" in x)
][
    [
    'opportunity_number',
    'opportunity_title',
    'category',
    'funding_categories',
    'summary_description',
    'applicant_types',
    'applicant_eligibility_description',
    'close_date',
    'award_floor',
    'award_ceiling',
    'expected_number_of_awards',
    'estimated_total_program_funding',
    'is_cost_sharing',
    'is_forecast',
    ]
].head(20)

,opportunity_number,opportunity_title,category,funding_categories,summary_description,applicant_types,applicant_eligibility_description,close_date,award_floor,award_ceiling,expected_number_of_awards,estimated_total_program_funding,is_cost_sharing,is_forecast
1011,DOT-HASS-FY26-DIIG,FY26 US DOT Drone Infrastructure Inspection Gr...,discretionary,community_development;consumer_protection;disa...,<p>The Drone Infrastructure Inspection Grants ...,county_governments;city_or_township_government...,An eligible applicant must be one of the follo...,NaN,500000.0,9000000.0,5.0,9000000.0,True,True

In [194]:
df[
    df["opportunity_number"]
    .fillna("")
    .str.split(";")
    .apply(lambda x: "FM-MCG-27-001" in x)
][
    [
    'opportunity_number',
    'opportunity_title',
    'category',
    'funding_categories',
    'summary_description',
    'applicant_types',
    'applicant_eligibility_description',
    'close_date',
    'award_floor',
    'award_ceiling',
    'expected_number_of_awards',
    'estimated_total_program_funding',
    'is_cost_sharing',
    'is_forecast',
    ]
].head(20)

,opportunity_number,opportunity_title,category,funding_categories,summary_description,applicant_types,applicant_eligibility_description,close_date,award_floor,award_ceiling,expected_number_of_awards,estimated_total_program_funding,is_cost_sharing,is_forecast
362,FM-MCG-27-001,Development of Fiscal Year 2027 Commercial Veh...,mandatory,transportation,The Motor Carrier Safety Assistance Program (M...,state_governments,NaN,2026-09-30,470000.0,55000000.0,56.0,494962500.0,True,False

In [195]:
df[
    df["opportunity_number"]
    .fillna("")
    .str.split(";")
    .apply(lambda x: "NHTSA-693JJ926R000024-FY26" in x)
][
    [
    'opportunity_number',
    'opportunity_title',
    'category',
    'funding_categories',
    'summary_description',
    'applicant_types',
    'applicant_eligibility_description',
    'close_date',
    'award_floor',
    'award_ceiling',
    'expected_number_of_awards',
    'estimated_total_program_funding',
    'is_cost_sharing',
    'is_forecast',
    ]
].head(20)

,opportunity_number,opportunity_title,category,funding_categories,summary_description,applicant_types,applicant_eligibility_description,close_date,award_floor,award_ceiling,expected_number_of_awards,estimated_total_program_funding,is_cost_sharing,is_forecast
719,NHTSA-693JJ926R000024-FY26,Innovative Traffic Safety Enforcement (ITSE) G...,discretionary,other,<p>While the agency will consider innovative e...,other;special_district_governments;state_gover...,Applicants eligible for an award include a Sta...,2027-09-01,300000.0,20000000.0,10.0,20000000.0,False,False

In [196]:
columns_needed = [
    'opportunity_number',
    'opportunity_title',
    'category',
    'funding_categories',
    'summary_description',
    'applicant_types',
    'applicant_eligibility_description',
    'close_date',
    'award_floor',
    'award_ceiling',
    'expected_number_of_awards',
    'estimated_total_program_funding',
    'is_cost_sharing',
    'is_forecast',
    'url'
]
grants = df[columns_needed].copy()

grants.head(20)

,opportunity_number,opportunity_title,category,funding_categories,summary_description,applicant_types,applicant_eligibility_description,close_date,award_floor,award_ceiling,expected_number_of_awards,estimated_total_program_funding,is_cost_sharing,is_forecast,url
0,O-OVW-2026-172633,OVW Fiscal Year 2026 Grants to Improve the Cri...,discretionary,law_justice_and_legal_services,"The ICJR Program assists Tribal, state, and lo...",city_or_township_governments;county_government...,Eligible applicants are limited to: State gove...,2026-08-18,400000.0,1500000.0,67.0,36000000.0,False,False,https://simpler.grants.gov/opportunity/3f8c97e...
1,PAR-25-051,Blueprint Neurotherapeutics Network (BPN): Sma...,discretionary,education;health,The Blueprint Neurotherapeutics Network (BPN) ...,city_or_township_governments;nonprofits_non_hi...,Other Eligible Applicants include the followin...,2026-08-18,NaN,NaN,NaN,NaN,False,False,https://simpler.grants.gov/opportunity/07f98e9...
2,HHS-2026-ACF-ACYF-AP-0003,Personal Responsibility Education Innovative S...,discretionary,income_security_and_social_services,The Personal Responsibility Education Program-...,county_governments;independent_school_district...,Applications from collaboratives and/or consor...,2026-08-18,750000.0,900000.0,12.0,10000000.0,False,False,https://simpler.grants.gov/opportunity/0f7454e...
3,23-618,"Decision, Risk and Management Sciences - Docto...",discretionary,science_technology_and_other_research_and_deve...,"The Decision, Risk and Management Sciences Pro...",other,*Who May Submit Proposals: Proposals may only ...,2026-08-18,NaN,NaN,30.0,675000.0,False,False,https://simpler.grants.gov/opportunity/a9a78fa...
4,SB-OIT-STEP-2026-01,State Trade Expansion Program 2026,discretionary,business_and_commerce,<p>State Trade Expansion Program</p>,private_institutions_of_higher_education;publi...,The Small Business Act provides in § 22(l)(1)(...,2026-08-18,100000.0,900000.0,55.0,NaN,True,False,https://simpler.grants.gov/opportunity/83f7a3f...
5,NNH25ZDA001N-RIA,ROSES25: F.17 Research Initiation Awards,discretionary,science_technology_and_other_research_and_deve...,"<p><strong>NOTICE: Amended May 20, 2026. This ...",other,Proposers must be affiliated with an instituti...,2026-08-18,NaN,NaN,NaN,NaN,False,False,https://simpler.grants.gov/opportunity/91d1747...
6,FR-CCD-24-023,FY24 Little Rock Port Authority Transload Yard...,discretionary,transportation,Little Rock Port Authority Transload Yard,city_or_township_governments,NaN,2026-08-18,0.0,11500000.0,1.0,11500000.0,True,False,https://simpler.grants.gov/opportunity/9c36e35...
7,PD-23-1321,"Decision, Risk and Management Sciences",discretionary,science_technology_and_other_research_and_deve...,"The Decision, Risk and Management Sciences Pro...",unrestricted,NaN,2026-08-18,NaN,NaN,NaN,NaN,False,False,https://simpler.grants.gov/opportunity/c223519...
8,USDA-FNA-SNAP-2026-EVS,FY 2026 SNAP Earnings Verification Support Grant,discretionary,food_and_nutrition,<p>The USDA’s Food and Nutrition Administratio...,state_governments,NaN,2026-08-19,1.0,4300000.0,53.0,38000000.0,False,False,https://simpler.grants.gov/opportunity/145d1cb...
9,HHS-2026-ACF-ACYF-CY-0160,National Communication System for Runaway and ...,discretionary,income_security_and_social_services,​​The Division of Runaway and Homeless Youth w...,independent_school_districts;federally_recogni...,In accordance with section 331 of the Runaway ...,2026-08-19,1000000.0,1800000.0,1.0,1800000.0,True,False,https://simpler.grants.gov/opportunity/2a188bd...
10,23-601,Research Experiences for Undergraduates,discretionary,science_technology_and_other_research_and_deve...,The Research Experiences for Undergraduates (R...,other,*Who May Serve as PI:\n\nFor REU Site proposal...,2026-08-19,5000.0,500000.0,1350.0,84800000.0,False,False,https://simpler.grants.gov/opportunity/19553c4...
11,PA-FPT-26-001,National Training Center for Family Planning,discretionary,health,The purpose of this funding opportunity is to ...,public_and_indian_housing_authorities;nonprofi...,Any public or private nonprofit entity is elig...,2026-08-19,0.0,3000000.0,1.0,3000000.0,False,False,https://simpler.grants.gov/opportunity/f58877b...
12,RFA-FD-26-012,Use of Digital Health Technologies in Clinical...,discretionary,agriculture;consumer_protection;food_and_nutri...,<p>The purpose of this Notice of Funding Oppor...,city_or_township_governments;for_profit_organi...,NaN,2026-08-20,0.0,1100000.0,2.0,NaN,False,False,https://simpler.grants.gov/opportunity/758eb23...
13,O-BJA-2026-172654,BJA FY 2025/2026 Project Safe Neighborhoods Fo...,other,law_justice_and_legal_services,This is a notice of funding opportunity (NOFO)...,other,Certified PSN Team fiscal agents for the feder...,2026-08-20,0.0,1187963.0,NaN,NaN,False,False,https://simpler.grants.gov/opportunity/7dbda48...
14,AMERICANSPACESSTARTUPLAB-2026,StartUP Lab: U.S.-Albania Economic Leadership...,discretionary,other,<p>1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<stro...,other,1.\tEligible Applicants \r\nThe following orga...,2026-08-20,10000.0,53400.0,1.0,53400.0,False,False,https://simpler.grants.gov/opportunity/b3fc2fa...
15,DFOP0019426,Leveraging Academic Institutions and Judicial ...,discretionary,other,"The U.S. Department of State, Bureau of Democr...",other,"- Not for profit organizations, including thin...",2026-08-20,1973359.0,1973359.0,1.0,0.0,False,False,https://simpler.grants.gov/opportunity/cfd01f0...
16,PDS-APS-FY26-01,"U.S-Nigeria Creative, Digital, & Innovation Ec...",discretionary,other,<p>The U.S. Department of State’s U.S. Consula...,private_institutions_of_higher_education;publi...,NaN,2026-08-20,20000.0,60000.0,10.0,500000.0,True,False,https://simpler.grants.gov/opportunity/b72b08c...
17,RFA-FD-26-009,Education and Outreach to Tribal Producers thr...,discretionary,agriculture;consumer_protection;food_and_nutri...,<p>The primary purpose of this program is to d...,other,Sole Source: The University of Arkansas,2026-08-20,0.0,500000.0,1.0,500000.0,False,False,https://simpler.grants.gov/opportunity/dfd2408...
18,DFOP0019193,Pax Silica Artificial Intelligence Assistance ...,discretionary,business_and_commerce,Leveraging foreign assistance from the Pax Fun...,for_profit_organizations_other_than_small_busi...,NaN,2026-08-20,1000000.0,50000000.0,3.0,0.0,False,False,https://simpler.grants.gov/opportunity/2f434e8...
19,AMERICANSPACESGAMEON-2026,GameON – U.S.-Albania E-Sports and Innovation,discretionary,other,"<strong style=""color: windowtext;""><em>1.&nbsp...",other,1.\tEligible Applicants\r\nThe following organ...,2026-08-20,3000.0,8000.0,1.0,8000.0,False,False,https://simpler.grants.gov/opportunity/9c2d325...

In [197]:
df[
    df["funding_categories"]
    .fillna("")
    .str.split(";")
    .apply(lambda x: "transportation" in x)
][
    [
        "opportunity_title",
        "funding_categories",
        "applicant_types",
        "close_date",
        "award_floor",
        "award_ceiling"
    ]
].head(20)

,opportunity_title,funding_categories,applicant_types,close_date,award_floor,award_ceiling
6,FY24 Little Rock Port Authority Transload Yard...,transportation,city_or_township_governments,2026-08-18,0.0,11500000.0
33,FY26 Transportation Emergency Response Training,transportation,other,2026-08-21,0.0,150000.0
57,FY 2026 Competitive Funding Opportunity: Publi...,transportation,federally_recognized_native_american_tribal_go...,2026-08-25,0.0,0.0
94,Small Business Transportation Technical Assist...,transportation,nonprofits_non_higher_education_without_501c3;...,2026-08-30,278272.0,278272.0
97,Small Business Transportation Technical Assist...,transportation,nonprofits_non_higher_education_without_501c3;...,2026-08-30,441559.0,441559.0
101,Small Business Transportation Technical Assist...,transportation,nonprofits_non_higher_education_without_501c3;...,2026-08-30,452420.0,452420.0
126,Fiscal Year 2026 United States Marine Highway ...,transportation,other,2026-08-31,1.0,12000000.0
209,FY26 - Stopping Threats On Pedestrian Competit...,infrastructure_investment_and_jobs_act;transpo...,state_governments;city_or_township_governments...,2026-09-09,0.0,5000000.0
210,FY 2026 Notice of Funding Opportunity: Innovat...,transportation,federally_recognized_native_american_tribal_go...,2026-09-09,0.0,0.0
245,FY25 and FY26 Advanced Digital Construction Ma...,infrastructure_investment_and_jobs_act;transpo...,state_governments,2026-09-16,1000000.0,5000000.0
264,Fiscal Year 2026 Competitive Funding Opportuni...,transportation,state_governments;federally_recognized_native_...,2026-09-21,0.0,0.0
267,Fiscal Year 2026 Competitive Funding Opportuni...,transportation,other;county_governments;city_or_township_gove...,2026-09-21,0.0,0.0
309,"FY26 Bus Safety, Accessibility, and Innovation...",transportation,city_or_township_governments;small_businesses;...,2026-09-28,0.0,10000000.0
362,Development of Fiscal Year 2027 Commercial Veh...,transportation,state_governments,2026-09-30,470000.0,55000000.0
724,FAA Aviation Research Grants Program,transportation,public_and_state_institutions_of_higher_educat...,2027-09-07,0.0,6000000.0
1011,FY26 US DOT Drone Infrastructure Inspection Gr...,community_development;consumer_protection;disa...,county_governments;city_or_township_government...,NaN,500000.0,9000000.0
1102,Joint Center of Excellence for Advanced Materi...,science_technology_and_other_research_and_deve...,other,NaN,0.0,20000000.0

In [198]:
# Categorizes applicant types eligibility
applicant_types = (
    df["applicant_types"]
    .fillna("")
    .str.split(";")
    .explode()
)

applicant_summary = (
    applicant_types
    .value_counts()
    .reset_index()
)

applicant_summary.columns = [
    "Applicant Type",
    "Number of Grants"
]

applicant_summary

                                       Applicant Type  Number of Grants
0                                               other              1151
1          nonprofits_non_higher_education_with_501c3               922
2   public_and_state_institutions_of_higher_education               912
3   federally_recognized_native_american_tribal_go...               900
4                                   state_governments               887
5            private_institutions_of_higher_education               879
6                                  county_governments               856
7          other_native_american_tribal_organizations               848
8                        city_or_township_governments               789
9       nonprofits_non_higher_education_without_501c3               787
10  for_profit_organizations_other_than_small_busi...               772
11                                   small_businesses               770
12                       independent_school_districts               766
13                       special_district_governments               762
14              public_and_indian_housing_authorities               747
15                                       unrestricted               276
16                                        individuals                20

In [199]:
# Hard filter 1: Eligibility for state government (NCDOT)
grants["eligibility_status"] = (
    grants["applicant_types"]
    .fillna("")
    .str.split(";")
    .apply(
        lambda x: (
            "Potentially eligible"
            if "state_governments" in x
            else "Not eligible"
        )
    )
)
eligible = grants[
    grants["eligibility_status"] == "Potentially eligible"
].copy()

eligible["funding_categories"] = (
    eligible["funding_categories"]
    .fillna("")
    .str.split(";")
)

category_summary = (
    eligible["funding_categories"]
    .explode()
    .value_counts()
    .reset_index()
)

category_summary.columns = [
    "Funding Category",
    "Number of Grants"
]

category_summary

                                     Funding Category  Number of Grants
0                                              health               722
1                                           education               121
2                 income_security_and_social_services                65
3                                  food_and_nutrition                62
4                                         environment                45
5                                         agriculture                39
6                                 consumer_protection                33
7                                   natural_resources                22
8                      law_justice_and_legal_services                21
9                                               other                20
10                                     transportation                11
11  science_technology_and_other_research_and_deve...                 9
12                                               arts                 8
13                                            housing                 7
14                     disaster_prevention_and_relief                 5
15                              community_development                 5
16                              business_and_commerce                 4
17                          opportunity_zone_benefits                 4
18                         information_and_statistics                 4
19                                         humanities                 3
20             infrastructure_investment_and_jobs_act                 2
21                      employment_labor_and_training                 1
22                                             energy                 1

In [200]:
# Recheck individual grants
grants[
    [
        "opportunity_title",
        "applicant_types",
        "eligibility_status"
    ]
].head(20)

,opportunity_title,applicant_types,eligibility_status
0,OVW Fiscal Year 2026 Grants to Improve the Cri...,city_or_township_governments;county_government...,Potentially eligible
1,Blueprint Neurotherapeutics Network (BPN): Sma...,city_or_township_governments;nonprofits_non_hi...,Potentially eligible
2,Personal Responsibility Education Innovative S...,county_governments;independent_school_district...,Potentially eligible
3,"Decision, Risk and Management Sciences - Docto...",other,Not eligible
4,State Trade Expansion Program 2026,private_institutions_of_higher_education;publi...,Potentially eligible
5,ROSES25: F.17 Research Initiation Awards,other,Not eligible
6,FY24 Little Rock Port Authority Transload Yard...,city_or_township_governments,Not eligible
7,"Decision, Risk and Management Sciences",unrestricted,Not eligible
8,FY 2026 SNAP Earnings Verification Support Grant,state_governments,Potentially eligible
9,National Communication System for Runaway and ...,independent_school_districts;federally_recogni...,Potentially eligible
10,Research Experiences for Undergraduates,other,Not eligible
11,National Training Center for Family Planning,public_and_indian_housing_authorities;nonprofi...,Potentially eligible
12,Use of Digital Health Technologies in Clinical...,city_or_township_governments;for_profit_organi...,Potentially eligible
13,BJA FY 2025/2026 Project Safe Neighborhoods Fo...,other,Not eligible
14,StartUP Lab: U.S.-Albania Economic Leadership...,other,Not eligible
15,Leveraging Academic Institutions and Judicial ...,other,Not eligible
16,"U.S-Nigeria Creative, Digital, & Innovation Ec...",private_institutions_of_higher_education;publi...,Not eligible
17,Education and Outreach to Tribal Producers thr...,other,Not eligible
18,Pax Silica Artificial Intelligence Assistance ...,for_profit_organizations_other_than_small_busi...,Not eligible
19,GameON – U.S.-Albania E-Sports and Innovation,other,Not eligible

In [201]:
# Split data by categories

grants["funding_categories"] = (
    grants["funding_categories"]
    .fillna("")
    .str.split(";")
)

grants[["opportunity_title", "funding_categories"]].head()

,opportunity_title,funding_categories
0,OVW Fiscal Year 2026 Grants to Improve the Cri...,[law_justice_and_legal_services]
1,Blueprint Neurotherapeutics Network (BPN): Sma...,"[education, health]"
2,Personal Responsibility Education Innovative S...,[income_security_and_social_services]
3,"Decision, Risk and Management Sciences - Docto...",[science_technology_and_other_research_and_dev...
4,State Trade Expansion Program 2026,[business_and_commerce]

In [202]:
eligible = grants[
    grants["eligibility_status"] == "Potentially eligible"
].copy()

In [203]:
all_categories = (
    eligible["funding_categories"]
    .explode()
)

all_categories.value_counts()

funding_categories
health                                                   722
education                                                121
income_security_and_social_services                       65
food_and_nutrition                                        62
environment                                               45
agriculture                                               39
consumer_protection                                       33
natural_resources                                         22
law_justice_and_legal_services                            21
other                                                     20
transportation                                            11
science_technology_and_other_research_and_development      9
arts                                                       8
housing                                                    7
disaster_prevention_and_relief                             5
community_development                                      5
business_and_commerce                                      4
opportunity_zone_benefits                                  4
information_and_statistics                                 4
humanities                                                 3
infrastructure_investment_and_jobs_act                     2
employment_labor_and_training                              1
energy                                                     1
Name: count, dtype: int64

In [204]:
# Convert close_date to datetime
eligible["close_date"] = pd.to_datetime(
    eligible["close_date"],
    errors="coerce"
)
today = pd.Timestamp("2026-09-25")

eligible["deadline_status"] = eligible["close_date"].apply(
    lambda x:
        "Missing deadline" if pd.isna(x)
        else "Future" if x >= today
        else "Passed"
)

eligible["deadline_status"].value_counts()

deadline_status
Future              394
Missing deadline    391
Passed              102
Name: count, dtype: int64

In [205]:
# Check how many grants have missing deadlines are forecast grants
eligible[
    eligible["close_date"].isna()
]["is_forecast"].value_counts(dropna=False)

is_forecast
True     382
False      9
Name: count, dtype: int64

In [206]:
# Hard filter 2: Remove grants with known deadlines that have already passed
eligible["close_date"] = pd.to_datetime(
    eligible["close_date"],
    errors="coerce"
)

reference_date = pd.Timestamp("2026-09-25")

eligible_open = eligible[
    eligible["close_date"].isna() |
    (eligible["close_date"] >= reference_date)
].copy()

In [207]:
# Hard filter 3: Remove forecasted grants
eligible_final = eligible_open[
    eligible_open["is_forecast"] == False
].copy()

In [208]:
eligible_final[
    eligible_final["opportunity_number"]
    .fillna("")
    .str.split(";")
    .apply(lambda x: "DOT-HASS-FY26-DIIG" in x)
][
    [
        "opportunity_title",
        "funding_categories",
        "applicant_types",
        "close_date",
        "award_floor",
        "award_ceiling",
    ]
].head(20)

Empty DataFrame
Columns: [opportunity_title, funding_categories, applicant_types, close_date, award_floor, award_ceiling]
Index: []

In [209]:
# Scoring: Funding categories
funding_category_scores = {
    "transportation": 10,
    "infrastructure_investment_and_jobs_act": 10,

    "disaster_prevention_and_relief": 3,
    "community_development": 2,
    "regional_development": 2,
    "science_technology_and_other_research_and_development": 2,
    "information_and_statistics": 2,

    "environment": 1,
    "energy": 1,
    "employment_labor_and_training": 1
}

def score_funding_category(categories):
    scores = []

    for category in categories:
        if category in funding_category_scores:
            scores.append(funding_category_scores[category])
        else:
            scores.append(0)

    return max(scores) if scores else 0

eligible_final["funding_category_score"] = (
    eligible_final["funding_categories"]
    .apply(score_funding_category)
)

In [210]:
# Scoring: Categories ((discretionary, mandatory, earmark, other)
def score_category(category):

    if category == "discretionary":
        return 3

    elif category == "mandatory":
        return 2

    elif category == "earmark":
        return 1

    else:
        return 0

eligible_final["category_score"] = (
    eligible_final["category"]
    .fillna("")
    .str.lower()
    .apply(score_category)
)

In [211]:
# Scoring: Close date
reference_date = pd.Timestamp("2026-09-25")

eligible_final["days_until_close"] = (
    eligible_final["close_date"] - reference_date
).dt.days

import numpy as np

def score_close_date(x):

    # Missing close date
    if pd.isna(x):
        return 0

    # More than 31 days away
    elif x > 31:
        return 15 / np.sqrt(x - 30)

    # Less than 30 days away
    elif 0 < x < 30:
        return -10 / np.sqrt(x)

    # Between 30 and 31 days
    elif 30 <= x <= 31:
        return 0

eligible_final["close_date_score"] = (
    eligible_final["days_until_close"]
    .apply(score_close_date)
)

In [212]:
# Scoring: Expected number of awards
import math
def score_expected_number_of_awards(x):

    if pd.isna(x):
        return 0

    elif x <= 0:
        return 0

    else:
        return int(
            (30 / (1 + math.exp(-0.1 * x))) - 15
        )
eligible_final["expected_awards_score"] = (
    eligible_final["expected_number_of_awards"]
    .apply(score_expected_number_of_awards)
)

In [213]:
# Scoring: Award average
def average_from_award_range(x):
    # -\_ graph
    scoring_max = 10
    scoring_min = -10
    if pd.isna(x) or x == 0:
        return 0
    try:
      output_score = np.clip(int((10 / (1 + math.exp(-x + 4) ) )), scoring_min, scoring_max)
    except OverflowError:
      return(scoring_max)
    return output_score
    #if x >= 0 else int(x) - 1


def award_average(ceiling, floor):
    # scores the award_average category for each grant as the average of the award_ceiling and award_floor columns
    # input: two numbers from the dataframe, award_ceiling and award_floor
    # output: the average of the two columns

    return (ceiling + floor) / 2


eligible_final["award_average"] = eligible_final.apply(
    lambda row: award_average(
        row["award_ceiling"],
        row["award_floor"]
    ),
    axis=1
)

awards_all_avg = eligible_final["award_average"].mean()

print(f"total average of award avgs: {awards_all_avg}")
print(( awards_all_avg - eligible_final["award_average"] ))

eligible_final["award_average_score"] = (
    ( eligible_final["award_average"] - awards_all_avg )
).apply(average_from_award_range)

total average of award avgs: 5772140.331168831
292              NaN
293              NaN
294              NaN
296     4.272140e+06
297     5.562140e+06
            ...
1297   -1.318579e+08
1369    5.622140e+06
1378   -9.277860e+06
1392    5.772140e+06
1590    5.622140e+06
Name: award_average, Length: 403, dtype: float64

In [214]:
# Scoring: Award average

def average_from_award_range(x):
    # Convert the normalized award difference into a score from 0 to 10
    # x = 0 means the grant's award average equals the overall award average
    # Positive x means the grant's award average is above the overall average
    # Negative x means the grant's award average is below the overall average

    if pd.isna(x):
        return np.nan

    return np.clip(
        10 / (1 + np.exp(-4 * x)),
        0,
        10
    )


def award_average(ceiling, floor):
    # Calculates the average award amount for each grant
    # input: award_ceiling and award_floor
    # output: average of award_ceiling and award_floor

    return (ceiling + floor) / 2


# Calculate the average award amount for each grant
eligible_final["award_average"] = eligible_final.apply(
    lambda row: award_average(
        row["award_ceiling"],
        row["award_floor"]
    ),
    axis=1
)


# Calculate the overall average award amount across all grants
awards_all_avg = eligible_final["award_average"].mean()

print(f"total average of award avgs: {awards_all_avg}")


# Normalize each grant's award average relative to the overall average
eligible_final["award_average_normalized"] = (
    (eligible_final["award_average"] - awards_all_avg)
    / awards_all_avg
)

print(eligible_final["award_average_normalized"])


# Convert the normalized difference into a score from 0 to 10
eligible_final["award_average_score"] = (
    eligible_final["award_average_normalized"]
    .apply(average_from_award_range)
)


# Check the results
print(
    eligible_final[
        [
            "award_floor",
            "award_ceiling",
            "award_average",
            "award_average_normalized",
            "award_average_score"
        ]
    ]
)

total average of award avgs: 5772140.331168831
292           NaN
293           NaN
294           NaN
296     -0.740131
297     -0.963618
          ...
1297    22.843842
1369    -0.974013
1378     1.607352
1392    -1.000000
1590    -0.974013
Name: award_average_normalized, Length: 403, dtype: float64
      award_floor  award_ceiling  award_average  award_average_normalized  \
292           NaN      1300000.0            NaN                       NaN
293           NaN            NaN            NaN                       NaN
294           NaN       350000.0            NaN                       NaN
296           0.0      3000000.0      1500000.0                 -0.740131
297       20000.0       400000.0       210000.0                 -0.963618
...           ...            ...            ...                       ...
1297     260000.0    275000000.0    137630000.0                 22.843842
1369          0.0       300000.0       150000.0                 -0.974013
1378     100000.0     30000000.0     15050000.0                  1.607352
1392          0.0            0.0            0.0                 -1.000000
1590          0.0       300000.0       150000.0                 -0.974013

      award_average_score
292                   NaN
293                   NaN
294                   NaN
296              0.492415
297              0.207453
...                   ...
1297            10.000000
1369             0.199172
1378             9.983892
1392             0.179862
1590             0.199172

[403 rows x 5 columns]

In [215]:
eligible_final[
    [
        "opportunity_title",
        "funding_categories",
        "funding_category_score",
        "category",
        "category_score",
        "close_date",
        "days_until_close",
        "close_date_score",
        "award_floor",
        "award_ceiling",
        "award_average",
        "expected_number_of_awards",
        "expected_awards_score"
    ]
].sample(20)

,opportunity_title,funding_categories,funding_category_score,category,category_score,close_date,days_until_close,close_date_score,award_floor,award_ceiling,award_average,expected_number_of_awards,expected_awards_score
757,NEI Research Grant for Vision-Related Secondar...,[health],0,discretionary,3,2027-10-16,386.0,0.794998,NaN,NaN,NaN,NaN,0
338,F26AS00069 Coastal Program FY26,[natural_resources],0,discretionary,3,2026-09-30,5.0,-4.472136,1.0,500000.0,250000.5,150.0,14
424,Assay Validation of High Quality Markers for C...,"[education, health]",0,discretionary,3,2026-10-14,19.0,-2.294157,NaN,250000.0,NaN,NaN,0
944,"NIH Research Education Program - Courses, Curr...",[health],0,discretionary,3,2029-05-25,973.0,0.488467,NaN,NaN,NaN,NaN,0
690,NIA Expanding Research in AD/ADRD (ERA) Summer...,[health],0,discretionary,3,2027-05-26,243.0,1.027783,NaN,200000.0,NaN,NaN,0
382,Limited Competition: Growing Great Ideas: Rese...,[health],0,discretionary,3,2026-10-01,6.0,-4.082483,NaN,NaN,NaN,1.0,0
524,"Ethical, Legal and Social Implications (ELSI) ...","[income_security_and_social_services, environm...",1,discretionary,3,2026-11-16,52.0,3.198011,NaN,50000.0,NaN,NaN,0
592,Developing novel theory and methods for unders...,"[health, education]",0,discretionary,3,2027-01-07,104.0,1.743715,NaN,NaN,NaN,NaN,0
660,Computational Approaches to Curation at Scale ...,"[health, education]",0,discretionary,3,2027-04-15,202.0,1.143739,NaN,250000.0,NaN,NaN,0
390,Expanding global health security through local...,[health],0,discretionary,3,2026-10-02,7.0,-3.779645,0.0,0.0,0.0,3.0,2
869,Community-Partnered Nursing Research Centers (...,"[education, health]",0,discretionary,3,2028-05-07,590.0,0.633866,NaN,500000.0,NaN,NaN,0
581,National Cancer Institute's Investigator-Initi...,"[education, health]",0,discretionary,3,2027-01-07,104.0,1.743715,NaN,499999.0,NaN,NaN,0
812,Clinical Characterization of Cancer Therapy-in...,"[health, education]",0,discretionary,3,2028-01-07,469.0,0.715911,NaN,NaN,NaN,NaN,0
555,Maximizing the Scientific Value of Data Genera...,[health],0,discretionary,3,2026-12-02,68.0,2.433321,NaN,NaN,NaN,8.0,5
666,NIH Pathway to Independence Award (Parent K99/...,"[income_security_and_social_services, environm...",1,discretionary,3,2027-05-07,224.0,1.076937,NaN,NaN,NaN,NaN,0
596,NHLBI Early Phase Clinical Trials for Therapeu...,[health],0,discretionary,3,2027-01-07,104.0,1.743715,NaN,NaN,NaN,NaN,0
731,NICHD Resource Program Grants in Bioinformatic...,"[income_security_and_social_services, health]",0,discretionary,3,2027-09-25,365.0,0.819538,NaN,NaN,NaN,NaN,0
767,National Cooperative Drug/Device Discovery/Dev...,[health],0,discretionary,3,2027-10-25,395.0,0.785136,NaN,NaN,NaN,NaN,0
367,HEAL INITIATIVE: INTERACT Data Coordination an...,[health],0,discretionary,3,2026-10-01,6.0,-4.082483,NaN,NaN,NaN,1.0,0
409,Development and Testing of a Multi-use Framewo...,[health],0,discretionary,3,2026-10-09,14.0,-2.672612,NaN,300000.0,NaN,5.0,3

In [216]:
print("Funding category score:")
print(eligible_final["funding_category_score"].value_counts().sort_index())

print("\nCategory score:")
print(eligible_final["category_score"].value_counts().sort_index())

print("\nClose date score:")
print(eligible_final["close_date_score"].value_counts().sort_index())

print("\nExpected number of awards score:")
print(eligible_final["expected_awards_score"].value_counts().sort_index())

print("\nAward average score:")
print(eligible_final["award_average_score"].value_counts().sort_index())

Funding category score:
funding_category_score
0     358
1      36
2       5
3       2
10      2
Name: count, dtype: int64

Category score:
category_score
2      2
3    401
Name: count, dtype: int64

Close date score:
close_date_score
-5.773503     7
-5.000000     4
-4.472136     9
-4.082483     4
-3.779645    12
             ..
 4.330127     1
 4.522670     3
 5.303301     2
 6.123724     5
 6.708204     4
Name: count, Length: 152, dtype: int64

Expected number of awards score:
expected_awards_score
0     316
1       8
2      22
3       8
4       3
5       9
6       7
8       1
9       2
10      2
11      6
12      3
13      2
14     12
15      2
Name: count, dtype: int64

Award average score:
award_average_score
0.179862     14
0.185454      1
0.186719      3
0.189276      1
0.189598      1
0.195818      3
0.197488      1
0.199172      7
0.202582      1
0.207453      1
0.209575      1
0.213159      1
0.213160      1
0.213883      1
0.216804      1
0.220509      1
0.224276      2
0.232000      1
0.244074      2
0.248234      1
0.263343      1
0.272374      1
0.274679      1
0.298791      1
0.324948      1
0.353313      1
0.377204      1
0.392899      1
0.449673      1
0.476444      1
0.492415      1
0.534589      1
0.534589      1
0.580155      1
0.655378      1
0.953309      1
1.030678      1
2.117035      1
2.752403      1
3.693327      2
6.632120      1
7.860581      1
9.529830      1
9.540773      1
9.756868      1
9.983892      1
9.999998      1
10.000000     1
10.000000     3
Name: count, dtype: int64

In [217]:
around_100k = eligible_final[
    eligible_final["award_average"].between(90_000, 110_000)
][
    [
        "opportunity_title",
        "award_floor",
        "award_ceiling",
        "award_average",
        "award_average_score"
    ]
]

around_100k.head(10)

Empty DataFrame
Columns: [opportunity_title, award_floor, award_ceiling, award_average, award_average_score]
Index: []

In [218]:
around_10m = eligible_final[
    eligible_final["award_average"].between(9_000_000, 11_000_000)
][
    [
        "opportunity_title",
        "award_floor",
        "award_ceiling",
        "award_average",
        "award_average_score"
    ]
]

around_10m.head(10)

,opportunity_title,award_floor,award_ceiling,award_average,award_average_score
476,RESTORE Act Centers of Excellence Research Gra...,5710210.0,14518510.0,10114360.0,9.529830
719,Innovative Traffic Safety Enforcement (ITSE) G...,300000.0,20000000.0,10150000.0,9.540773

In [219]:
# Normalize each scoring criterion to 0-1
score_columns = [
    "funding_category_score",
    "category_score",
    "award_average_score",
    "expected_awards_score",
    "close_date_score"
]

for col in score_columns:
    min_score = eligible_final[col].min()
    max_score = eligible_final[col].max()

    eligible_final[col + "_normalized"] = (
        eligible_final[col] - min_score
    ) / (
        max_score - min_score
    )

# Score calculation
eligible_final["total_score"] = (
    eligible_final["funding_category_score_normalized"] * 0.65
    + eligible_final["category_score_normalized"] * 0.05
    + eligible_final["award_average_score_normalized"] * 0.15
    + eligible_final["expected_awards_score_normalized"] * 0.05
    + eligible_final["close_date_score_normalized"] * 0.10
)

# Scale to 0-100
eligible_final["total_score"] = (
    eligible_final["total_score"] * 100
)

In [220]:
eligible_final[
    [
        "opportunity_title",
        "funding_category_score",
        "category_score",
        "close_date_score",
        "award_average_score",
        "expected_awards_score",
        "total_score"
    ]
].sample(20)

,opportunity_title,funding_category_score,category_score,close_date_score,award_average_score,expected_awards_score,total_score
528,Prevention and Intervention Approaches for Fet...,0,3,3.127716,NaN,0,NaN
560,Specialty Crop Multi-State Grant Program 2026,0,3,2.371708,0.274679,11,15.337216
660,Computational Approaches to Curation at Scale ...,0,3,1.143739,NaN,0,NaN
732,Clinical and Translational Science Award (UM1 ...,0,3,0.815892,NaN,0,NaN
798,NIDCR Behavioral and Social Intervention Clini...,0,3,0.716728,NaN,0,NaN
476,RESTORE Act Centers of Excellence Research Gra...,2,3,6.123724,9.529830,3,42.813559
778,Pilot Projects Investigating Understudied Prot...,0,3,0.762493,NaN,0,NaN
832,Development of Biomarkers or Composite Biomark...,0,3,0.715911,NaN,0,NaN
395,Expanding global health security though local ...,0,3,-3.779645,0.179862,2,7.264091
836,Dissemination and Implementation Research in H...,1,3,0.715911,NaN,0,NaN
344,"International Programs & Trade, Invasive Speci...",1,3,-4.472136,0.195818,2,13.233659
787,Catalyze: Product Definition Medical Device P...,0,3,0.728464,NaN,0,NaN
847,The Role of Work in Health Disparities in the ...,0,3,0.715911,NaN,0,NaN
757,NEI Research Grant for Vision-Related Secondar...,0,3,0.794998,NaN,0,NaN
694,Enhancing Mechanistic Research on Precision Pr...,0,3,1.011300,NaN,0,NaN
699,BRAIN Initiative: Reagent Resources for Brain ...,0,3,0.982683,NaN,0,NaN
704,NHLBI Career Transition Award for Intramural P...,0,3,0.930261,NaN,0,NaN
585,Mechanisms that Impact Cancer Risk with Use of...,0,3,1.743715,NaN,0,NaN
804,Exploratory/Developmental Bioengineering Resea...,0,3,0.715911,NaN,0,NaN
403,Advancing Research on the Application of Digit...,0,3,-3.015113,NaN,0,NaN

In [221]:
ranked_grants = eligible_final.sort_values(
    by="total_score",
    ascending=False
)

ranked_grants[
    [
        "opportunity_title",
        "total_score",
        "funding_categories",
        "category",
        "close_date",
        'award_floor',
        'award_ceiling',
       'expected_number_of_awards',
    ]
].head(5)

,opportunity_title,total_score,funding_categories,category,close_date,award_floor,award_ceiling,expected_number_of_awards
362,Development of Fiscal Year 2027 Commercial Veh...,85.709282,[transportation],mandatory,2026-09-30,470000.0,55000000.0,56.0
309,"FY26 Bus Safety, Accessibility, and Innovation...",75.700057,[transportation],discretionary,2026-09-28,0.0,10000000.0,2.0
476,RESTORE Act Centers of Excellence Research Gra...,42.813559,[science_technology_and_other_research_and_dev...,discretionary,2026-10-31,5710210.0,14518510.0,5.0
473,RESTORE Act Direct Component - Non-Constructio...,31.531731,[other],discretionary,2026-10-31,0.0,120153261.0,10.0
474,RESTORE Act Direct Component – Construction an...,31.531731,[other],discretionary,2026-10-31,0.0,120153261.0,10.0

In [222]:
transportation_grants = eligible_final[
    eligible_final["funding_categories"].apply(
        lambda x: "transportation" in x
    )
].copy()

transportation_grants[
    [
        "opportunity_title",
        "funding_categories",
        "category",
        "close_date",
        "funding_category_score",
        "award_average_score",
        "expected_awards_score",
        "close_date_score",
        "total_score"
    ]
].sort_values(
    "total_score",
    ascending=False
)

,opportunity_title,funding_categories,category,close_date,funding_category_score,award_average_score,expected_awards_score,close_date_score,total_score
362,Development of Fiscal Year 2027 Commercial Veh...,[transportation],mandatory,2026-09-30,10,9.999998,14,-4.472136,85.709282
309,"FY26 Bus Safety, Accessibility, and Innovation...",[transportation],discretionary,2026-09-28,10,3.693327,1,-5.773503,75.700057

In [223]:
transportation_grants[
    ["opportunity_title", "total_score"]
].sort_values(
    "total_score",
    ascending=False
)

print("Number of transportation grants:", len(transportation_grants))

Number of transportation grants: 2