<a href="https://colab.research.google.com/github/sheninyee/sdis-solvathon-2026-team-theSouperSolvers/blob/main/solveathon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [73]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [74]:
data_path = '/content/drive/My Drive/grants-search-202608182008.csv'
df = pd.read_csv(data_path)

df.info()
df.head(60)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1662 entries, 0 to 1661
Data columns (total 40 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   opportunity_id                     1662 non-null   object
 1   opportunity_number                 1662 non-null   object
 2   opportunity_title                  1662 non-null   object
 3   opportunity_status                 1662 non-null   object
 4   agency_code                        1662 non-null   object
 5   category                           1662 non-null   object
 6   category_explanation               29 non-null     object
 7   post_date                          1662 non-null   object
 8   close_date                         1005 non-null   object
 9   close_date_description             291 non-null    object
 10  archive_date                       954 non-null    object
 11  is_cost_sharing                    1662 non-null   bool
 12  expected_number_of_awards          940 non-null    float64
 13  estimated_total_program_funding    914 non-null    float64
 14  award_floor                        664 non-null    float64
 15  award_ceiling                      798 non-null    float64
 16  additional_info_url                757 non-null    object
 17  additional_info_url_description    741 non-null    object
 18  opportunity_assistance_listings    1661 non-null   object
 19  funding_instruments                1662 non-null   object
 20  funding_categories                 1662 non-null   object
 21  funding_category_description       143 non-null    object
 22  applicant_types                    1662 non-null   object
 23  applicant_eligibility_description  1285 non-null   object
 24  agency_name                        1662 non-null   object
 25  top_level_agency_name              1662 non-null   object
 26  agency_contact_description         1662 non-null   object
 27  agency_email_address               1613 non-null   object
 28  agency_email_address_description   1608 non-null   object
 29  is_forecast                        1662 non-null   bool
 30  forecasted_post_date               473 non-null    object
 31  forecasted_close_date              499 non-null    object
 32  forecasted_close_date_description  151 non-null    object
 33  forecasted_award_date              453 non-null    object
 34  forecasted_project_start_date      459 non-null    object
 35  fiscal_year                        559 non-null    float64
 36  created_at                         0 non-null      float64
 37  updated_at                         0 non-null      float64
 38  url                                1662 non-null   object
 39  summary_description                1662 non-null   object
dtypes: bool(2), float64(7), object(31)
memory usage: 496.8+ KB

,opportunity_id,opportunity_number,opportunity_title,opportunity_status,agency_code,category,category_explanation,post_date,close_date,close_date_description,...,forecasted_post_date,forecasted_close_date,forecasted_close_date_description,forecasted_award_date,forecasted_project_start_date,fiscal_year,created_at,updated_at,url,summary_description
0,3f8c97e2-901a-44c4-b9ac-b6b941c29d42,O-OVW-2026-172633,OVW Fiscal Year 2026 Grants to Improve the Cri...,posted,USDOJ-OJP-OVW,discretionary,NaN,2026-06-04,2026-08-18,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/3f8c97e...,"The ICJR Program assists Tribal, state, and lo..."
1,07f98e93-9564-44cf-ab5c-69ca0cfa218f,PAR-25-051,Blueprint Neurotherapeutics Network (BPN): Sma...,posted,HHS-NIH11,discretionary,NaN,2024-09-25,2026-08-18,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/07f98e9...,The Blueprint Neurotherapeutics Network (BPN) ...
2,0f7454eb-e5b6-458a-86eb-4d874a9f9d8f,HHS-2026-ACF-ACYF-AP-0003,Personal Responsibility Education Innovative S...,posted,HHS-ACF-FYSB,discretionary,NaN,2026-07-17,2026-08-18,Electronically submitted applications must be ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/0f7454e...,The Personal Responsibility Education Program-...
3,a9a78fab-33d8-4a34-a2de-c7571df8b19b,23-618,"Decision, Risk and Management Sciences - Docto...",posted,NSF,discretionary,NaN,2023-08-25,2026-08-18,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/a9a78fa...,"The Decision, Risk and Management Sciences Pro..."
4,83f7a3f7-9a94-46dc-b9da-d8300efb69c1,SB-OIT-STEP-2026-01,State Trade Expansion Program 2026,posted,SBA,discretionary,NaN,2026-07-10,2026-08-18,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/83f7a3f...,<p>State Trade Expansion Program</p>
5,91d17473-9a2e-433b-8daa-a76f47721574,NNH25ZDA001N-RIA,ROSES25: F.17 Research Initiation Awards,posted,NASA-HQ,discretionary,NaN,2026-05-20,2026-08-18,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/91d1747...,"<p><strong>NOTICE: Amended May 20, 2026. This ..."
6,9c36e35a-beae-4bf4-9bb1-ef5927677555,FR-CCD-24-023,FY24 Little Rock Port Authority Transload Yard...,posted,DOT-FRA,discretionary,NaN,2026-08-12,2026-08-18,No Explanation,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/9c36e35...,Little Rock Port Authority Transload Yard
7,c2235197-1004-43b5-b0e4-ee599d64fd13,PD-23-1321,"Decision, Risk and Management Sciences",posted,NSF,discretionary,NaN,2023-05-11,2026-08-18,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/c223519...,"The Decision, Risk and Management Sciences Pro..."
8,145d1cb2-34a7-4f79-b927-341045f54938,USDA-FNA-SNAP-2026-EVS,FY 2026 SNAP Earnings Verification Support Grant,posted,USDA-FNS1,discretionary,NaN,2026-07-16,2026-08-19,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/145d1cb...,<p>The USDA’s Food and Nutrition Administratio...
9,2a188bdf-3d4a-4021-9f9d-dafce74537ba,HHS-2026-ACF-ACYF-CY-0160,National Communication System for Runaway and ...,posted,HHS-ACF-FYSB,discretionary,NaN,2026-07-21,2026-08-19,Electronically submitted applications must be ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/2a188bd...,​​The Division of Runaway and Homeless Youth w...
10,19553c47-f333-4b57-b6c3-74f38305903f,23-601,Research Experiences for Undergraduates,posted,NSF,discretionary,NaN,2023-06-29,2026-08-19,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/19553c4...,The Research Experiences for Undergraduates (R...
11,f58877bf-d0ad-43f7-8ae4-92382f4e0d0d,PA-FPT-26-001,National Training Center for Family Planning,posted,HHS-OPHS,discretionary,NaN,2026-07-02,2026-08-19,Applications must be submitted electronically ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/f58877b...,The purpose of this funding opportunity is to ...
12,758eb232-aa13-4c39-a651-e6429d961b03,RFA-FD-26-012,Use of Digital Health Technologies in Clinical...,posted,HHS-FDA,discretionary,NaN,2026-07-20,2026-08-20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/758eb23...,<p>The purpose of this Notice of Funding Oppor...
13,7dbda489-7738-473c-a407-2e15b7799566,O-BJA-2026-172654,BJA FY 2025/2026 Project Safe Neighborhoods Fo...,posted,USDOJ-OJP-BJA,other,Formula,2026-07-13,2026-08-20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/7dbda48...,This is a notice of funding opportunity (NOFO)...
14,b3fc2fad-6829-4466-a040-8e5d7df3b6fc,AMERICANSPACESSTARTUPLAB-2026,StartUP Lab: U.S.-Albania Economic Leadership...,posted,DOS-ALB,discretionary,NaN,2026-07-20,2026-08-20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/b3fc2fa...,<p>1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<stro...
15,cfd01f0a-d9c5-42c4-89e3-445d2b1bf16d,DFOP0019426,Leveraging Academic Institutions and Judicial ...,posted,DOS-DRL,discretionary,NaN,2026-07-21,2026-08-20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/cfd01f0...,"The U.S. Department of State, Bureau of Democr..."
16,b72b08c2-cfde-4c1c-9ba2-deb5e9aec8a5,PDS-APS-FY26-01,"U.S-Nigeria Creative, Digital, & Innovation Ec...",posted,DOS-NGA,discretionary,NaN,2026-07-22,2026-08-20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/b72b08c...,<p>The U.S. Department of State’s U.S. Consula...
17,dfd24081-d0e0-4630-8988-bbe1ee8f2689,RFA-FD-26-009,Education and Outreach to Tribal Producers thr...,posted,HHS-FDA,discretionary,NaN,2026-07-20,2026-08-20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/dfd2408...,<p>The primary purpose of this program is to d...
18,2f434e81-c476-49bb-a7e6-9a320c907cd9,DFOP0019193,Pax Silica Artificial Intelligence Assistance ...,posted,DOS-EB,discretionary,NaN,2026-08-14,2026-08-20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/2f434e8...,Leveraging foreign assistance from the Pax Fun...
19,9c2d325f-bb42-4d98-b60b-65422a5c38b8,AMERICANSPACESGAMEON-2026,GameON – U.S.-Albania E-Sports and Innovation,posted,DOS-ALB,discretionary,NaN,2026-07-20,2026-08-20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/9c2d325...,"<strong style=""color: windowtext;""><em>1.&nbsp..."
20,9f4e0eea-6330-4011-8742-617103f10bd8,PDS-BUE-2026-07,Subnational Industrial Innovation and Resilien...,posted,DOS-ARG,discretionary,NaN,2026-07-27,2026-08-20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/9f4e0ee...,<p>The U.S. Embassy Buenos Aires announces an ...
21,c9928432-25de-46e2-96b7-f4d3cb4ca7b0,AMERICANSPACESCYBERNEXT-2026,CyberNext: Advance Cybersecurity and AI Readiness,posted,DOS-ALB,discretionary,NaN,2026-07-20,2026-08-20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/c992843...,"<p><strong style=""color: black;""><em>Project B..."
22,c36eed46-2c0c-46e0-830a-c15274a1ee00,PDS-BUE-2026-06,U.S.-Argentina Alumni Summit,posted,DOS-ARG,discretionary,NaN,2026-07-27,2026-08-20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/c36eed4...,<p>The U.S. Embassy Buenos Aires announces an ...
23,cf7687ca-0614-44a6-8f46-08723d8df092,DHS-26-NPD-107-00-01,Fiscal Year 2026 National Incident Management ...,posted,DHS-DHS,mandatory,NaN,2026-07-17,2026-08-20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/cf7687c...,<p>The purpose of the Fiscal Year (FY) 2026 NI...
24,14e416ba-c983-42f9-be72-003e5f8b4a28,HHS-2026-ACF-ACYF-CO-0040,Technology Enhanced Adoptive Family Recruiting...,posted,HHS-ACF-CB,discretionary,NaN,2026-07-22,2026-08-21,Electronically submitted applications must be ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/14e416b...,This program will fund projects focused on tec...
25,64b21b29-7210-4d55-9630-29a9bbdf9dd8,RFA-FD-26-011,"Research, Education, and Outreach on Botanical...",posted,HHS-FDA,discretionary,NaN,2026-07-22,2026-08-21,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/64b21b2...,<p>The purpose of this funding opportunity is ...
26,da9ea956-a099-4ac0-ae24-3f9b001ee9a0,DOS-KAZ-ALM-PDS-26-001,Access Alumni Outreach and Engagement and Engl...,posted,DOS-KAZ,discretionary,NaN,2026-07-21,2026-08-21,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/da9ea95...,<p><strong>Funding Instrument Type:</strong> C...
27,f21ed65a-a584-4f18-b035-67652078ad06,DOS-LONDON-PD-2026-02,Liberty Under Law: The Shared Anglo-American T...,posted,DOS-GBR,discretionary,NaN,2026-07-20,2026-08-21,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/f21ed65...,"<p><span style=""color: black;"">The U.S. Depart..."
28,361be62f-48af-4751-b81e-5c829eecdafa,DFOP0019542,Promoting Civilizational Values,posted,DOS-DRL,discretionary,NaN,2026-08-07,2026-08-21,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/361be62...,DRL requests proposals to strengthen the abili...
29,1be83608-dcf2-4539-97fa-414d4c8ecaaa,2026-NIST-MEP-02,Manufacturing Extension Partnership Center Sta...,posted,DOC-NIST,discretionary,NaN,2026-07-22,2026-08-21,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/1be8360...,<p>The NIST Hollings Manufacturing Extension P...
30,92a87e8d-25fb-45d6-9b24-5143f0315a67,DFOP0018157,Data Analytics & AI to Counter Global Diversion,posted,DOS-ACN,discretionary,NaN,2026-07-16,2026-08-21,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/92a87e8...,This effort seeks to address multiple facets o...
31,d2e906e4-b4b0-40d3-b20c-12c22bbddfe0,RFA-FD-26-013,Cooperative Agreement to Support Shellfish Saf...,posted,HHS-FDA,discretionary,NaN,2026-07-22,2026-08-21,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/d2e906e...,<p>The purpose of this funding opportunity is ...
32,10c0d584-b356-49d0-8173-0e94a2eab1f5,RFA-FD-26-014,Federal and University Partnership to Improve ...,posted,HHS-FDA,discretionary,NaN,2026-07-23,2026-08-21,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/10c0d58...,<p>FDA is announcing the availability of funds...
33,9ea32117-e3af-440c-b8e3-00d3dd847463,FR-SEC-26-001,FY26 Transportation Emergency Response Training,posted,DOT-FRA,discretionary,NaN,2026-08-13,2026-08-21,No Explanation,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/9ea3211...,This grant will fund training for emergency re...
34,eb9d4f93-e7c5-4b6f-981e-b734308d39ea,O-OVC-2026-172691,OVC FY26 Invited to Apply Antiterrorism and Em...,posted,USDOJ-OJP-OVC,discretionary,NaN,2026-08-14,2026-08-21,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/eb9d4f9...,This is a notice of funding opportunity (NOFO)...
35,09b890ab-146f-4934-9309-ffe72fddd30f,USDA-NRCS-NHQ-RCPP-CLASSIC-26-NOFO000145,Regional Conservation Partnership Program (RCP...,posted,USDA-NRCS,discretionary,NaN,2026-06-23,2026-08-24,Applications must be received proposals by 4:5...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/09b890a...,<p><strong>Federal Awarding Agency Name: </str...
36,b8e41bf2-055d-4bde-bd67-144994abd33a,O-COPS-2026-172548,FY26 Collaborative Reform Initiative Program,posted,USDOJ-OJP-COPS,discretionary,NaN,2026-07-14,2026-08-24,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/b8e41bf...,The Office of Community Oriented Policing Serv...
37,7a05ac21-62c8-4c13-95de-2d5e8e80f851,FY26-PDS-USASEAN-02,2027 YSEALI ScamShield Regional Workshop,posted,DOS-ASEAN,discretionary,NaN,2026-07-22,2026-08-24,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/7a05ac2...,<p>The Public Diplomacy Sections (PDS) of the ...
38,239e6683-c301-4ee2-9794-cda512a24de5,HHS-2026-ACF-OCS-EAH-0027,Affordable Housing and Supportive Services Dem...,posted,HHS-ACF-OCS,discretionary,NaN,2026-07-24,2026-08-24,Electronically submitted applications must be ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/239e668...,The Office of Community Services (OCS) intends...
39,53569914-4323-4110-9680-2b264f0ae7d9,HHS-2026-ACF-OPRE-PV-0114,Reflective Supervision in Home Visiting Resear...,posted,HHS-ACF-OPRE,discretionary,NaN,2026-07-24,2026-08-24,Electronically submitted applications must be ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/5356991...,"The Office of Planning, Research and Evaluatio..."
40,09440b99-1e9a-4a02-b5cd-1549b83877b3,DFOP0018829,FY 2027 International Visitor Leadership Progr...,posted,DOS-ECA,discretionary,NaN,2026-06-24,2026-08-24,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/09440b9...,<p>The United States Department of State’s Bur...
41,86d33083-e00e-4d5b-b5e5-dac2693db06e,HHS-2026-ACF-OCS-ET-0029,Community Services Block Grant (CSBG) Communit...,posted,HHS-ACF-OCS,discretionary,NaN,2026-07-24,2026-08-24,Electronically submitted applications must be ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/86d3308...,This NOFO is modified. The email address and p...
42,e2d850ad-cd5d-4af4-82df-ba31865f7568,USDA-NRCS-NHQ-RCPP-AFA-26-NOFO0001451,Regional Conservation Partnership Program (RCP...,posted,USDA-NRCS,discretionary,NaN,2026-06-23,2026-08-24,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/e2d850a...,<p><br></p> \n<p><br></p> \n<p><strong>Federal...
43,6fda9fa9-8a53-48c8-b6a1-761fe0683635,HT942526LRPIPA,"DoW Lupus, Impact Award",posted,DOD-AMRAA,discretionary,NaN,2026-05-05,2026-08-24,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/6fda9fa...,<p>Summary: This funding mechanism supports hi...
44,795c0a29-510b-4b57-893a-d627b533ea6d,HT942526LRPIA,"DoW Lupus, Idea Award",posted,DOD-AMRAA,discretionary,NaN,2026-05-05,2026-08-24,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/795c0a2...,<p>Summary: This funding mechanism supports in...
45,5208056f-6e60-4509-8105-8bebd2ccab29,HT942526LRPTVDA,"DoW Lupus, Transformative Vision Development A...",posted,DOD-AMRAA,discretionary,NaN,2026-05-05,2026-08-24,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/5208056...,<p>Summary: This funding mechanism supports pl...
46,3ce9aff2-1ad9-4f82-abbf-3c44732640d8,HHS-2026-ACF-OCS-ET-0028,Community Services Block Grant (CSBG) Tribal C...,posted,HHS-ACF-OCS,discretionary,NaN,2026-07-24,2026-08-24,Electronically submitted applications must be ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/3ce9aff...,This NOFO is modified. The email address and p...
47,7f133801-c0e7-4967-826d-ed2419fa6206,SB-OEDNA-26-001,ONAA 7J-TCU Manufacturing NOFO FY2026,posted,SBA,discretionary,NaN,2026-07-24,2026-08-24,No Explanation,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/7f13380...,<p>The purpose of this Funding Opportunity Ann...
48,8fedc0bf-621a-4832-885c-8ae17b290747,O-COPS-2026-172561,FY26 Community Policing Development: Law Enfor...,posted,USDOJ-OJP-COPS,discretionary,NaN,2026-07-14,2026-08-24,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/8fedc0b...,The Office of Community Oriented Policing Serv...
49,a045e8e8-60f2-427a-b6d1-80f9d588dcbb,HHS-2026-ACF-OCS-ET-0030,Community Services Block Grant (CSBG) Essentia...,posted,HHS-ACF-OCS,discretionary,NaN,2026-07-24,2026-08-24,Electronically submitted applications must be ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/a045e8e...,This NOFO is modified. The email address and p...
50,e4d552b0-307d-4181-a6b9-92618d3963a3,HHS-2026-ACF-OCS-ET-0031,Community Services Block Grant (CSBG) Performa...,posted,HHS-ACF-OCS,discretionary,NaN,2026-07-24,2026-08-24,Electronically submitted applications must be ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/e4d552b...,This NOFO is modified. The email address and p...
51,e30a01a0-4ef9-466c-bed8-1bd2a9ef92b3,HT942526LRPTVA,"DoW Lupus, Transformative Vision Award",posted,DOD-AMRAA,discretionary,NaN,2026-05-05,2026-08-24,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/e30a01a...,<p>Summary: This funding mechanism supports in...
52,f867961f-f4de-47b1-8b18-51ddbe5531d6,O-COPS-2026-172560,FY26 Collaborative Reform Organizational Asses...,posted,USDOJ-OJP-COPS,discretionary,NaN,2026-07-14,2026-08-24,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/f867961...,The Office of Community Oriented Policing Serv...
53,56b71085-ed91-4468-b7eb-3a04bf840794,HR001126S0010,Decentralized Artificial Intelligence through ...,posted,DOD-DARPA-IPTO,discretionary,NaN,2026-06-10,2026-08-25,See Full Announcement for details.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/56b7108...,The DICE program seeks to develop the theory a...
54,c82c7aab-1dcf-4e82-8f18-86107c3bcf25,O-BJA-2026-172684,OJP FY 2026 Special Attorneys Program Round 7,posted,USDOJ-OJP-BJA,discretionary,NaN,2026-08-12,2026-08-25,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/c82c7aa...,This is a notice of funding opportunity (NOFO)...
55,b88775b5-9db4-4d78-861a-860df9449cd7,OFOP0003144,Enhancing Prison Population Management Through...,posted,DOS-INL,discretionary,NaN,2026-06-30,2026-08-25,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/b88775b...,"The project will divert low-risk, first-time o..."
56,ea961e6e-f500-482e-84e2-b7d9a7a6105b,23-586,Robert Noyce Teacher Scholarship Program,posted,NSF,discretionary,NaN,2023-05-09,2026-08-25,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/ea961e6...,The National Science FoundationRobert Noyce Te...
57,392cf284-d976-44c8-8515-265a3134e49a,FTA-2026-002-TPM-TRTR,FY 2026 Competitive Funding Opportunity: Publi...,posted,DOT-FTA,discretionary,NaN,2026-05-27,2026-08-25,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/392cf28...,<p>The Federal Transit Administration (FTA) an...
58,1115c1ae-29fe-4c8c-a8c0-b1541ee6d285,DFOP0019436,Legal Competency and Training Program in South...,posted,DOS-EAP,discretionary,NaN,2026-07-23,2026-08-25,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/1115c1a...,The overall goal of the project is to strength...
59,deb21960-8b7b-4507-84fd-3ad7a24fb22d,HHS-2026-ACL-AOA-LAEP-0055,Legal Assistance Enhancement Program Grants,posted,HHS-ACL,discretionary,NaN,2026-06-29,2026-08-25,Electronically submitted applications must be ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://simpler.grants.gov/opportunity/deb2196...,To carry out Older Americans Act Section 307(a...

In [75]:
print(df.shape)

(1662, 40)

In [76]:
columns_needed = [
    'opportunity_number',
    'opportunity_title',
    'category',
    'funding_categories',
    'summary_description',
    'applicant_types',
    'applicant_eligibility_description',
    'close_date',
    'award_floor',
    'award_ceiling',
    'estimated_total_program_funding',
    'is_cost_sharing',
    'is_forecast',
    'url'
]
grants = df[columns_needed].copy()

grants.head(20)

,opportunity_number,opportunity_title,category,funding_categories,summary_description,applicant_types,applicant_eligibility_description,close_date,award_floor,award_ceiling,estimated_total_program_funding,is_cost_sharing,is_forecast,url
0,O-OVW-2026-172633,OVW Fiscal Year 2026 Grants to Improve the Cri...,discretionary,law_justice_and_legal_services,"The ICJR Program assists Tribal, state, and lo...",city_or_township_governments;county_government...,Eligible applicants are limited to: State gove...,2026-08-18,400000.0,1500000.0,36000000.0,False,False,https://simpler.grants.gov/opportunity/3f8c97e...
1,PAR-25-051,Blueprint Neurotherapeutics Network (BPN): Sma...,discretionary,education;health,The Blueprint Neurotherapeutics Network (BPN) ...,city_or_township_governments;nonprofits_non_hi...,Other Eligible Applicants include the followin...,2026-08-18,NaN,NaN,NaN,False,False,https://simpler.grants.gov/opportunity/07f98e9...
2,HHS-2026-ACF-ACYF-AP-0003,Personal Responsibility Education Innovative S...,discretionary,income_security_and_social_services,The Personal Responsibility Education Program-...,county_governments;independent_school_district...,Applications from collaboratives and/or consor...,2026-08-18,750000.0,900000.0,10000000.0,False,False,https://simpler.grants.gov/opportunity/0f7454e...
3,23-618,"Decision, Risk and Management Sciences - Docto...",discretionary,science_technology_and_other_research_and_deve...,"The Decision, Risk and Management Sciences Pro...",other,*Who May Submit Proposals: Proposals may only ...,2026-08-18,NaN,NaN,675000.0,False,False,https://simpler.grants.gov/opportunity/a9a78fa...
4,SB-OIT-STEP-2026-01,State Trade Expansion Program 2026,discretionary,business_and_commerce,<p>State Trade Expansion Program</p>,private_institutions_of_higher_education;publi...,The Small Business Act provides in § 22(l)(1)(...,2026-08-18,100000.0,900000.0,NaN,True,False,https://simpler.grants.gov/opportunity/83f7a3f...
5,NNH25ZDA001N-RIA,ROSES25: F.17 Research Initiation Awards,discretionary,science_technology_and_other_research_and_deve...,"<p><strong>NOTICE: Amended May 20, 2026. This ...",other,Proposers must be affiliated with an instituti...,2026-08-18,NaN,NaN,NaN,False,False,https://simpler.grants.gov/opportunity/91d1747...
6,FR-CCD-24-023,FY24 Little Rock Port Authority Transload Yard...,discretionary,transportation,Little Rock Port Authority Transload Yard,city_or_township_governments,NaN,2026-08-18,0.0,11500000.0,11500000.0,True,False,https://simpler.grants.gov/opportunity/9c36e35...
7,PD-23-1321,"Decision, Risk and Management Sciences",discretionary,science_technology_and_other_research_and_deve...,"The Decision, Risk and Management Sciences Pro...",unrestricted,NaN,2026-08-18,NaN,NaN,NaN,False,False,https://simpler.grants.gov/opportunity/c223519...
8,USDA-FNA-SNAP-2026-EVS,FY 2026 SNAP Earnings Verification Support Grant,discretionary,food_and_nutrition,<p>The USDA’s Food and Nutrition Administratio...,state_governments,NaN,2026-08-19,1.0,4300000.0,38000000.0,False,False,https://simpler.grants.gov/opportunity/145d1cb...
9,HHS-2026-ACF-ACYF-CY-0160,National Communication System for Runaway and ...,discretionary,income_security_and_social_services,​​The Division of Runaway and Homeless Youth w...,independent_school_districts;federally_recogni...,In accordance with section 331 of the Runaway ...,2026-08-19,1000000.0,1800000.0,1800000.0,True,False,https://simpler.grants.gov/opportunity/2a188bd...
10,23-601,Research Experiences for Undergraduates,discretionary,science_technology_and_other_research_and_deve...,The Research Experiences for Undergraduates (R...,other,*Who May Serve as PI:\n\nFor REU Site proposal...,2026-08-19,5000.0,500000.0,84800000.0,False,False,https://simpler.grants.gov/opportunity/19553c4...
11,PA-FPT-26-001,National Training Center for Family Planning,discretionary,health,The purpose of this funding opportunity is to ...,public_and_indian_housing_authorities;nonprofi...,Any public or private nonprofit entity is elig...,2026-08-19,0.0,3000000.0,3000000.0,False,False,https://simpler.grants.gov/opportunity/f58877b...
12,RFA-FD-26-012,Use of Digital Health Technologies in Clinical...,discretionary,agriculture;consumer_protection;food_and_nutri...,<p>The purpose of this Notice of Funding Oppor...,city_or_township_governments;for_profit_organi...,NaN,2026-08-20,0.0,1100000.0,NaN,False,False,https://simpler.grants.gov/opportunity/758eb23...
13,O-BJA-2026-172654,BJA FY 2025/2026 Project Safe Neighborhoods Fo...,other,law_justice_and_legal_services,This is a notice of funding opportunity (NOFO)...,other,Certified PSN Team fiscal agents for the feder...,2026-08-20,0.0,1187963.0,NaN,False,False,https://simpler.grants.gov/opportunity/7dbda48...
14,AMERICANSPACESSTARTUPLAB-2026,StartUP Lab: U.S.-Albania Economic Leadership...,discretionary,other,<p>1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<stro...,other,1.\tEligible Applicants \r\nThe following orga...,2026-08-20,10000.0,53400.0,53400.0,False,False,https://simpler.grants.gov/opportunity/b3fc2fa...
15,DFOP0019426,Leveraging Academic Institutions and Judicial ...,discretionary,other,"The U.S. Department of State, Bureau of Democr...",other,"- Not for profit organizations, including thin...",2026-08-20,1973359.0,1973359.0,0.0,False,False,https://simpler.grants.gov/opportunity/cfd01f0...
16,PDS-APS-FY26-01,"U.S-Nigeria Creative, Digital, & Innovation Ec...",discretionary,other,<p>The U.S. Department of State’s U.S. Consula...,private_institutions_of_higher_education;publi...,NaN,2026-08-20,20000.0,60000.0,500000.0,True,False,https://simpler.grants.gov/opportunity/b72b08c...
17,RFA-FD-26-009,Education and Outreach to Tribal Producers thr...,discretionary,agriculture;consumer_protection;food_and_nutri...,<p>The primary purpose of this program is to d...,other,Sole Source: The University of Arkansas,2026-08-20,0.0,500000.0,500000.0,False,False,https://simpler.grants.gov/opportunity/dfd2408...
18,DFOP0019193,Pax Silica Artificial Intelligence Assistance ...,discretionary,business_and_commerce,Leveraging foreign assistance from the Pax Fun...,for_profit_organizations_other_than_small_busi...,NaN,2026-08-20,1000000.0,50000000.0,0.0,False,False,https://simpler.grants.gov/opportunity/2f434e8...
19,AMERICANSPACESGAMEON-2026,GameON – U.S.-Albania E-Sports and Innovation,discretionary,other,"<strong style=""color: windowtext;""><em>1.&nbsp...",other,1.\tEligible Applicants\r\nThe following organ...,2026-08-20,3000.0,8000.0,8000.0,False,False,https://simpler.grants.gov/opportunity/9c2d325...

In [77]:
# Categorizes applicant types eligibility
applicant_types = (
    df["applicant_types"]
    .fillna("")
    .str.split(";")
    .explode()
)

applicant_summary = (
    applicant_types
    .value_counts()
    .reset_index()
)

applicant_summary.columns = [
    "Applicant Type",
    "Number of Grants"
]

applicant_summary

                                       Applicant Type  Number of Grants
0                                               other              1151
1          nonprofits_non_higher_education_with_501c3               922
2   public_and_state_institutions_of_higher_education               912
3   federally_recognized_native_american_tribal_go...               900
4                                   state_governments               887
5            private_institutions_of_higher_education               879
6                                  county_governments               856
7          other_native_american_tribal_organizations               848
8                        city_or_township_governments               789
9       nonprofits_non_higher_education_without_501c3               787
10  for_profit_organizations_other_than_small_busi...               772
11                                   small_businesses               770
12                       independent_school_districts               766
13                       special_district_governments               762
14              public_and_indian_housing_authorities               747
15                                       unrestricted               276
16                                        individuals                20

In [78]:
# Hard filter 1: Eligibility for state government (NCDOT)
grants["eligibility_status"] = (
    grants["applicant_types"]
    .fillna("")
    .str.split(";")
    .apply(
        lambda x: (
            "Potentially eligible"
            if "state_governments" in x
            else "Not eligible"
        )
    )
)
eligible = grants[
    grants["eligibility_status"] == "Potentially eligible"
].copy()

eligible["funding_categories"] = (
    eligible["funding_categories"]
    .fillna("")
    .str.split(";")
)

category_summary = (
    eligible["funding_categories"]
    .explode()
    .value_counts()
    .reset_index()
)

category_summary.columns = [
    "Funding Category",
    "Number of Grants"
]

category_summary

                                     Funding Category  Number of Grants
0                                              health               722
1                                           education               121
2                 income_security_and_social_services                65
3                                  food_and_nutrition                62
4                                         environment                45
5                                         agriculture                39
6                                 consumer_protection                33
7                                   natural_resources                22
8                      law_justice_and_legal_services                21
9                                               other                20
10                                     transportation                11
11  science_technology_and_other_research_and_deve...                 9
12                                               arts                 8
13                                            housing                 7
14                     disaster_prevention_and_relief                 5
15                              community_development                 5
16                              business_and_commerce                 4
17                          opportunity_zone_benefits                 4
18                         information_and_statistics                 4
19                                         humanities                 3
20             infrastructure_investment_and_jobs_act                 2
21                      employment_labor_and_training                 1
22                                             energy                 1

In [79]:
# Recheck individual grants
grants[
    [
        "opportunity_title",
        "applicant_types",
        "eligibility_status"
    ]
].head(20)

,opportunity_title,applicant_types,eligibility_status
0,OVW Fiscal Year 2026 Grants to Improve the Cri...,city_or_township_governments;county_government...,Potentially eligible
1,Blueprint Neurotherapeutics Network (BPN): Sma...,city_or_township_governments;nonprofits_non_hi...,Potentially eligible
2,Personal Responsibility Education Innovative S...,county_governments;independent_school_district...,Potentially eligible
3,"Decision, Risk and Management Sciences - Docto...",other,Not eligible
4,State Trade Expansion Program 2026,private_institutions_of_higher_education;publi...,Potentially eligible
5,ROSES25: F.17 Research Initiation Awards,other,Not eligible
6,FY24 Little Rock Port Authority Transload Yard...,city_or_township_governments,Not eligible
7,"Decision, Risk and Management Sciences",unrestricted,Not eligible
8,FY 2026 SNAP Earnings Verification Support Grant,state_governments,Potentially eligible
9,National Communication System for Runaway and ...,independent_school_districts;federally_recogni...,Potentially eligible
10,Research Experiences for Undergraduates,other,Not eligible
11,National Training Center for Family Planning,public_and_indian_housing_authorities;nonprofi...,Potentially eligible
12,Use of Digital Health Technologies in Clinical...,city_or_township_governments;for_profit_organi...,Potentially eligible
13,BJA FY 2025/2026 Project Safe Neighborhoods Fo...,other,Not eligible
14,StartUP Lab: U.S.-Albania Economic Leadership...,other,Not eligible
15,Leveraging Academic Institutions and Judicial ...,other,Not eligible
16,"U.S-Nigeria Creative, Digital, & Innovation Ec...",private_institutions_of_higher_education;publi...,Not eligible
17,Education and Outreach to Tribal Producers thr...,other,Not eligible
18,Pax Silica Artificial Intelligence Assistance ...,for_profit_organizations_other_than_small_busi...,Not eligible
19,GameON – U.S.-Albania E-Sports and Innovation,other,Not eligible

In [80]:
# Split data by categories

grants["funding_categories"] = (
    grants["funding_categories"]
    .fillna("")
    .str.split(";")
)

grants[["opportunity_title", "funding_categories"]].head()

,opportunity_title,funding_categories
0,OVW Fiscal Year 2026 Grants to Improve the Cri...,[law_justice_and_legal_services]
1,Blueprint Neurotherapeutics Network (BPN): Sma...,"[education, health]"
2,Personal Responsibility Education Innovative S...,[income_security_and_social_services]
3,"Decision, Risk and Management Sciences - Docto...",[science_technology_and_other_research_and_dev...
4,State Trade Expansion Program 2026,[business_and_commerce]

In [81]:
eligible = grants[
    grants["eligibility_status"] == "Potentially eligible"
].copy()

In [82]:
all_categories = (
    eligible["funding_categories"]
    .explode()
)

all_categories.value_counts()

funding_categories
health                                                   722
education                                                121
income_security_and_social_services                       65
food_and_nutrition                                        62
environment                                               45
agriculture                                               39
consumer_protection                                       33
natural_resources                                         22
law_justice_and_legal_services                            21
other                                                     20
transportation                                            11
science_technology_and_other_research_and_development      9
arts                                                       8
housing                                                    7
disaster_prevention_and_relief                             5
community_development                                      5
business_and_commerce                                      4
opportunity_zone_benefits                                  4
information_and_statistics                                 4
humanities                                                 3
infrastructure_investment_and_jobs_act                     2
employment_labor_and_training                              1
energy                                                     1
Name: count, dtype: int64

In [83]:
# Convert close_date to datetime
eligible["close_date"] = pd.to_datetime(
    eligible["close_date"],
    errors="coerce"
)
today = pd.Timestamp("2026-09-25")

eligible["deadline_status"] = eligible["close_date"].apply(
    lambda x:
        "Missing deadline" if pd.isna(x)
        else "Future" if x >= today
        else "Passed"
)

eligible["deadline_status"].value_counts()

deadline_status
Future              394
Missing deadline    391
Passed              102
Name: count, dtype: int64

In [84]:
# Check how many grants have missing deadlines are forecast grants
eligible[
    eligible["close_date"].isna()
]["is_forecast"].value_counts(dropna=False)

is_forecast
True     382
False      9
Name: count, dtype: int64

In [85]:
# Hard filter 2: Grants that deadlines have already passed
eligible["close_date"] = pd.to_datetime(
    eligible["close_date"],
    errors="coerce"
)

reference_date = pd.Timestamp("2026-09-25")

eligible_open = eligible[
    eligible["close_date"].isna() |
    (eligible["close_date"] >= reference_date)
].copy()

In [86]:
# Scoring: Funding categories
funding_category_scores = {
    "transportation": 3,
    "infrastructure_investment_and_jobs_act": 3,

    "disaster_prevention_and_relief": 2,
    "community_development": 2,
    "regional_development": 2,
    "science_technology_and_other_research_and_development": 2,
    "information_and_statistics": 2,

    "environment": 1,
    "energy": 1,
    "employment_labor_and_training": 1
}

def score_funding_category(categories):
    scores = []

    for category in categories:
        if category in funding_category_scores:
            scores.append(funding_category_scores[category])
        else:
            scores.append(0)

    return max(scores) if scores else 0

eligible_open["funding_category_score"] = (
    eligible_open["funding_categories"]
    .apply(score_funding_category)
)

In [87]:
# Scoring: Categories ((discretionary, mandatory, earmark, other)
def score_category(category):

    if category == "discretionary":
        return 3

    elif category == "mandatory":
        return 2

    elif category == "earmark":
        return 1

    else:
        return 0

eligible_open["category_score"] = (
    eligible_open["category"]
    .fillna("")
    .str.lower()
    .apply(score_category)
)

In [88]:
# Scoring: Cost sharing?
def score_cost_sharing(cost_sharing):

    if cost_sharing == True:
        return -5

    else:
        return 0

eligible_open["cost_sharing_score"] = (
    eligible_open["is_cost_sharing"]
    .apply(score_cost_sharing)
)

In [89]:
# Scoring: Forecast?
def score_forecast(is_forecast):

    if is_forecast == True:
        return -1

    else:
        return 0

eligible_open["forecast_score"] = (
    eligible_open["is_forecast"]
    .apply(score_forecast)
)

In [90]:
# Scoring: Close date
reference_date = pd.Timestamp("2026-09-25")

eligible_open["days_until_close"] = (
    eligible_open["close_date"] - reference_date
).dt.days

import numpy as np

def score_close_date(x):

    # Missing close date
    if pd.isna(x):
        return 0

    # More than 31 days away
    elif x > 31:
        return 15 / np.sqrt(x - 30)

    # Less than 30 days away
    elif 0 < x < 30:
        return -10 / np.sqrt(x)

    # Between 30 and 31 days
    elif 30 <= x <= 31:
        return 0

eligible_open["close_date_score"] = (
    eligible_open["days_until_close"]
    .apply(score_close_date)
)

In [91]:
eligible_open[
    [
        "opportunity_title",
        "funding_categories",
        "funding_category_score",
        "category",
        "category_score",
        "is_cost_sharing",
        "cost_sharing_score",
        "is_forecast",
        "forecast_score",
        "close_date",
        "days_until_close",
        "close_date_score"
    ]
].sample(20)

,opportunity_title,funding_categories,funding_category_score,category,category_score,is_cost_sharing,cost_sharing_score,is_forecast,forecast_score,close_date,days_until_close,close_date_score
679,NIDCD Research Career Enhancement Award for Es...,[health],0,discretionary,3,False,0,False,0,2027-05-07,224.0,1.076937
1080,Pancreatic Cancer Detection Consortium: Manage...,[health],0,discretionary,3,False,0,True,-1,NaT,NaN,0.000000
863,Environmental influences on Child Health Outco...,[health],0,discretionary,3,False,0,False,0,2028-03-01,523.0,0.675566
600,HEAL Initiative: Studies to Enable Analgesic D...,"[income_security_and_social_services, health, ...",0,discretionary,3,False,0,False,0,2027-01-15,112.0,1.656473
1054,Tobacco Centers of Regulatory Science (TCORS) ...,[health],0,discretionary,3,False,0,True,-1,NaT,NaN,0.000000
1379,Developing PBPK Model-Based Mechanistic IVIVCs...,"[health, food_and_nutrition, science_technolog...",2,discretionary,3,False,0,True,-1,NaT,NaN,0.000000
1408,Assay Validation of High Quality Markers for C...,[health],0,discretionary,3,False,0,True,-1,NaT,NaN,0.000000
643,NEA Arts and Artifacts International Indemnity...,[arts],0,discretionary,3,True,-5,False,0,2027-03-08,164.0,1.295803
1494,Development and Maintenance of Human and Anima...,"[food_and_nutrition, consumer_protection, agri...",0,discretionary,3,False,0,True,-1,NaT,NaN,0.000000
1495,Rural Health Network Development Planning Program,[health],0,discretionary,3,False,0,True,-1,NaT,NaN,0.000000
1343,Cooperative Agreement to Support a Human Abuse...,"[consumer_protection, agriculture, food_and_nu...",0,discretionary,3,False,0,True,-1,NaT,NaN,0.000000
1061,The NIDDK Disorders of Gastrointestinal Intero...,[health],0,discretionary,3,False,0,True,-1,NaT,NaN,0.000000
581,National Cancer Institute's Investigator-Initi...,"[education, health]",0,discretionary,3,False,0,False,0,2027-01-07,104.0,1.743715
1018,Investigate Novel Therapeutic Interventions an...,[health],0,discretionary,3,False,0,True,-1,NaT,NaN,0.000000
664,NHLBI Emerging Investigator Award (EIA) (R35 C...,[health],0,discretionary,3,False,0,False,0,2027-04-28,215.0,1.102822
765,Cancer Prevention and Control Clinical Trials ...,"[education, health]",0,discretionary,3,False,0,False,0,2027-10-25,395.0,0.785136
1383,Notice of Intent to Publish a Funding Opportun...,[health],0,discretionary,3,False,0,True,-1,NaT,NaN,0.000000
668,Mentored Quantitative Research Development Awa...,"[environment, education, food_and_nutrition, h...",1,discretionary,3,False,0,False,0,2027-05-07,224.0,1.076937
1591,High-Priority Research in Tobacco Regulatory S...,[health],0,discretionary,3,False,0,True,-1,NaT,NaN,0.000000
304,Institutional Training Programs to Advance Tra...,[health],0,discretionary,3,False,0,False,0,2026-09-25,0.0,NaN

In [92]:
print("Funding category score:")
print(eligible_open["funding_category_score"].value_counts().sort_index())

print("\nCategory score:")
print(eligible_open["category_score"].value_counts().sort_index())

print("\nCost sharing score:")
print(eligible_open["cost_sharing_score"].value_counts().sort_index())

print("\nForecast score:")
print(eligible_open["forecast_score"].value_counts().sort_index())

print("\nClose date score:")
print(eligible_open["close_date_score"].value_counts().sort_index())

Funding category score:
funding_category_score
0    734
1     36
2     12
3      3
Name: count, dtype: int64

Category score:
category_score
0      3
2      7
3    775
Name: count, dtype: int64

Cost sharing score:
cost_sharing_score
-5     35
 0    750
Name: count, dtype: int64

Forecast score:
forecast_score
-1    382
 0    403
Name: count, dtype: int64

Close date score:
close_date_score
-5.773503     7
-5.000000     4
-4.472136     9
-4.082483     4
-3.779645    12
             ..
 4.330127     1
 4.522670     3
 5.303301     2
 6.123724     5
 6.708204     4
Name: count, Length: 152, dtype: int64